function [data, auxData, metaData, txtData, weights] = mydata_Bactrocera_oleae
% file generated by prt_mydata

%% set metaData
metaData.phylum     = 'Arthropoda';
metaData.class      = 'Insecta';
metaData.order      = 'Diptera';
metaData.family     = 'Tephritidae';
metaData.species    = 'Bactrocera_oleae';
metaData.species_en = 'Olive fruit fly';

metaData.ecoCode.climate = {'BWh','BSh','Csa','Csb'};
metaData.ecoCode.ecozone = {'THp','TN'};
metaData.ecoCode.habitat = {'0iT'};
metaData.ecoCode.embryo  = {'Th'};
metaData.ecoCode.migrate = {};
metaData.ecoCode.food    = {'biH'};
metaData.ecoCode.gender  = {'Dg'};
metaData.ecoCode.reprod  = {'A'};

metaData.T_typical  = C2K(25); % K, body temp

metaData.data_0     = {'ab'; 'am'; 'tj'; 'te';  'Lj';  'Le';  'L_inst';  'Ww0';  'Wwj'; 'Ri'};
metaData.data_1     = {'tL-T'; 'tWw_f'; 'T_ab'; 'T_tj'; 'T_te'; 'TS'; 'tR'};

metaData.COMPLETE   = 4; % using criteria of LikaKear2011

metaData.author     = {'Evridiki Klagkou'};
metaData.date_subm  = [2025 06 24];
metaData.email      = {'biop1070@edu.biology.uoc.gr'};
metaData.address    = {'Univ of Crete'};

metaData.curator    = {'Bas Kooijman'};
metaData.email_cur  = {'bas.kooijman@vu.nl'};
metaData.date_acc   = [2025 06 25];

%% set zero-variate data
data.ab = 2.7;      units.ab = 'd';      label.ab = 'age at birth';                bibkey.ab = 'HaniNati2008';
    temp.ab = C2K(27);   units.temp.ab = 'K'; label.temp.ab = 'temperature';
data.am = 98.2; units.am = 'd'; label.am = 'life span'; bibkey.am = 'PappBrou2011';
  temp.am = C2K(25); units.temp.am = 'K'; label.temp.am = 'temperature';
  comment.am = 'imago longevity for females (control)';
data.tj = 13; units.tj = 'd'; label.tj = 'time since birth at pupation'; bibkey.tj = 'Hani2008';
  temp.tj = C2K(26); units.temp.tj = 'K'; label.temp.tj = 'temperature';
  comment.tj = 'larval duration for olive group';
data.te = 7; units.te = 'd'; label.te = 'time since pupation at emergence'; bibkey.te = 'Hani2008';
  temp.te = C2K(26); units.temp.te = 'K'; label.temp.te = 'temperature';
  comment.te = 'pupal duration at control food experiment';

data.Lj = 0.514; units.Lj  = 'cm';   label.Lj  = 'length at pupation';     bibkey.Lj  = 'HaniNati2008a';
    comment.Lj = 'length at pupation';
data.Le = 0.587; units.Le  = 'cm';   label.Le  = 'length at emergence';     bibkey.Le  = 'HaniNati2008a';
    comment.Le = 'length at emergence';    
data.L1 = 0.39; units.L1 = 'cm'; label.L1 = 'body length of instar 1'; bibkey.L1 = 'Shar1980';
data.L2 = 0.54; units.L2 = 'cm'; label.L2 = 'body length of instar 2'; bibkey.L2 = 'Shar1980';
data.L3 = 0.7; units.L3 = 'cm'; label.L3 = 'body length of instar 3'; bibkey.L3 = 'Shar1980';
 
data.Ww0 = 0.01; units.Ww0 = 'g'; label.Ww0 = 'wet weight of the egg'; bibkey.Ww0 = 'HaniNati2008a';
  comment.Ww0 = 'wet weight of egg';
data.Wwj = 0.00668; units.Wwj = 'g'; label.Wwj = 'wet weight at pupation'; bibkey.Wwj = 'Hani2008';
  comment.Wwj = 'mature larva weight at control food experiment';

data.Ri = 19; units.Ri = '#/d'; label.Ri = 'ultimate reproduction rate'; bibkey.Ri = 'HaniNati2008a';
  temp.Ri = C2K(24); units.temp.Ri = 'K'; label.temp.Ri = 'temperature';
  comment.Ri = 'imago fecundity';

%% univariate data
% temperature-age at birth
data.T_ab = [... % temperature (C), age at birth (d)
    16  11.40
    22  4.30
    27  2.67
    35  2.13];
units.T_ab   = {'C', 'd'};  label.T_ab = {'temperature', 'age at birth'};
bibkey.T_ab  = 'HaniNati2008';

% temperature-larval development
data.T_tj = [... % temperature (C), duration of larva (d)
    16  33.40
    22  14.13
    27  10.86
    35  5.06];
units.T_tj   = {'C', 'd'};  label.T_tj = {'temperature', 'duration of larva'};
bibkey.T_tj  = 'HaniNati2008';

% temperature-pupal development
data.T_te = [... % temperature (C), duration of pupa (d)
    16  28.40
    22  12.67
    27  8.26];
units.T_te   = {'C', 'd'};  label.T_te = {'temperature', 'duration of pupa'};
bibkey.T_te  = 'HaniNati2008';

% temperature-egg development rate
data.T_re = [... % temperature (C), egg development rate (1/d)
    16  0.12
    22  0.27
    27  0.37
    35  0.5];
units.T_re   = {'C', '1/d'};  label.T_re = {'temperature', 'egg development rate'};
bibkey.T_re  = 'HaniNati2008';

% temperature-larval development rate
data.T_rl = [... % temperature (C), larva development rate (1/d)
    16  0.04
    22  0.10
    27  0.17
    35  0.31];
units.T_rl   = {'C', '1/d'};  label.T_rl = {'temperature', 'larva development rate'};
bibkey.T_rl  = 'HaniNati2008a';

% temperature-pupal development rate
data.T_rp = [... % temperature (C), pupa development rate (1/d)
    16  0.044
    22  0.108
    27  0.172];
units.T_rp   = {'C', '1/d'};  label.T_rp = {'temperature', 'pupa development rate'};
bibkey.T_rp  = 'HaniNati2008a';

% temperature-egg survival
data.TS_b = [... % temperature (C), survival eggs (%)
%     25  87.5
    34  70
    36  80
    38  72.5
    39  30
    40  12.5
    42  0];
units.TS_b   = {'C', '%'};  label.TS_b = {'temperature', 'egg survival'};
bibkey.TS_b  = 'PappBrou2011';

% temperature-pupal survival
data.TS_p = [... % temperature (C), survival pupae (%)
%     25  98
    34  94
    36  94
    38  86
    40  74
    42  0];
units.TS_p   = {'C', '%'};  label.TS_p = {'temperature', 'pupae survival'};
bibkey.TS_p  = 'PappBrou2011';

% temperature-imago survival
data.TS_i = [... % temperature (C), survival imago (%)
%     25  100
    36  100
    37  100
    38  95
    39  20];
units.TS_i   = {'C', '%'};  label.TS_i = {'temperature', 'imago survival'};
bibkey.TS_i  = 'PappBrou2011';
comment.TS_i = 'data for females';

% time-number of eggs
data.tR = [... % time (d), number of eggs (#/d)
   1 8.7
   2 14.9
   3 15.9
   4 14.4
   5 13.4
   6 11.8
   7 20.6];
data.tR(:,2) = cumsum(data.tR(:,2));
units.tR  = {'d', '#/d'};  label.tR = {'oviposition day', 'number of eggs per day'};
temp.tR = C2K(25); units.temp.tR = 'K'; label.temp.tR = 'temperature';
bibkey.tR  = 'SancFern2012';

% time-survival
data.tS_cold = [... % time (d), survival (%)
  1   89
  3.2 83
  4.8 78.1
  8   78.1
  10  73.5
  13.6 68.9
  18 63.19
  21.2  59.2
  26.8 46.76
  29.2 42.8
  33.2 37.9
  39.6  30.6
  44  22.7
  53.66 17.232
  60.469 14.181
  75.6 9.5
  82.494 6.848
  90.5 3.79];
units.tS_cold  = {'d', '%'};  label.tS_cold = {'time after emergence', 'survival'};
temp.tS_cold= C2K(26); units.temp.tS_cold = 'K'; label.temp.tS_cold = 'temperature';
bibkey.tS_cold  = 'Yoko2012';

% time-length
data.tL_14 = [... % time (d), larval length (mm)
  6.7  0.6
  7.9  0.6
  8.8  0.663
  10.8 0.725
  12.28 0.820
  14.10 0.818
  15.8 0.913
  17.95 0.91
  20.730 1.068
  21.105 1.608
  25.949 2.27
  27.116 3.336
  29.77 3.838
  31.78 4.730
  33.7 5.239];
units.tL_14  = {'d', 'mm'};  label.tL_14 = {'time after birth', 'length', '14 C'};
temp.tL_14= C2K(14); units.temp.tL_14 = 'K'; label.temp.tL_14 = 'temperature';
bibkey.tL_14  = 'Yoko2012';
%
data.tL_21 = [... % time (d), larval length (mm)
  4  0.779
  5.8 0.83
  7.91 1.1
  9.8 2.06
  12.08 2.89
  13.15 3.9
  14.97 4.325];
units.tL_21  = {'d', 'mm'};  label.tL_21 = {'time after birth', 'length', '21 C'};
temp.tL_21= C2K(21); units.temp.tL_21 = 'K'; label.temp.tL_21 = 'temperature';
bibkey.tL_21  = 'Yoko2012';
%
data.tL_26 = [... % time (d), larval length (mm)
  3.2  0.67
  5.2  0.98
  7.27  1.23
  8.2 2.3
  9.2  2.91
  10  4.4
  12.1 5.16
  13.9 5.27];
units.tL_26  = {'d', 'mm'};  label.tL_26 = {'time after birth', 'length', '26 C'};
temp.tL_26= C2K(26); units.temp.tL_26 = 'K'; label.temp.tL_26 = 'temperature';
bibkey.tL_26  = 'Yoko2012';

% time-weight
data.tWw_f = [... % time (d), larval weight (mg)
   1    0.04   0.04    0.04    0.04
   2    0.11   0.09    0.08    0.10
   3    0.25   0.20    0.19    0.21
   4    0.48   0.42    0.41    0.43
   5    1.27   0.98    0.80    0.68
   6    2.50   1.93    1.80    1.72
   7    4.54   4.25    2.18    2.14
   8    5.58   5.82    4.13    4.06
   9    7.32   6.03    4.67    3.95];
data.tWw_f(:,2:5) = data.tWw_f(:,2:5)/ 10^3; % convert mg to g
units.tWw_f  = {'d', 'g'};  label.tWw_f = {'time after birth', 'wet weight'};
temp.tWw_f= C2K(25); units.temp.tWw_f = 'K'; label.temp.tWw_f = 'temperature';
treat.tWw_f = {1 {'10','20','40','60'}}; label.treat.tWw_f = 'larvae density';
bibkey.tWw_f  = 'Mano1980';

%% set weights for all real data
weights = setweights(data, []);
weights.tL_14 = 3 * weights.tL_14;
weights.tL_21 = 3 * weights.tL_21;
weights.tL_26 = 3 * weights.tL_26;
weights.Ww0 = 3* weights.Ww0;

%% set pseudodata and respective weights
[data, units, label, weights] = addpseudodata(data, units, label, weights);

%% pack auxData and txtData for output
auxData.temp = temp;
auxData.treat = treat;
txtData.units = units;
txtData.label = label;
txtData.bibkey = bibkey;
txtData.comment = comment;

%% Group plots
set1 = {'tL_26', 'tL_21', 'tL_14'}; subtitle1 = {'Larval length at 26, 21, 14 C'};
metaData.grp.sets = {set1};  
metaData.grp.subtitle = {subtitle1};

%% Discussion points

%% Links
metaData.links.id_CoL = '87RHN'; % Cat of Life
metaData.links.id_ITIS = '673027'; % ITIS
metaData.links.id_EoL = '724421'; % Ency of Life
metaData.links.id_Wiki = 'Bactrocera_oleae'; % Wikipedia
metaData.links.id_ADW = 'Bactrocera_oleae'; % ADW
metaData.links.id_Taxo = '3693115'; % Taxonomicon
metaData.links.id_WoRMS = ''; % WoRMS

%% References
bibkey = 'Hani2008'; type = 'article'; bib = [ ...
'author = {Hanife Gen\c{c}}, ' ... 
'title = {Modified Agar-based Diet for Small Scale Laboratory rearing of Olive Fruit Fly, \emph{Bactrocera oleae} ({D}iptera:{T}ephritidae)}, ' ... 
'journal = {Florida Entomologist}, ' ... 
'year = {2008}, ' ... 
'volume = {91}, ' ... 
'pages = {651-656}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'Kooy2010'; type = 'Book'; bib = [ ...  % used in setting of chemical parameters and pseudodata
'author = {Kooijman, S.A.L.M.}, ' ...
'year = {2010}, ' ...
'title  = {Dynamic Energy Budget theory for metabolic organisation}, ' ...
'publisher = {Cambridge Univ. Press, Cambridge}, ' ...
'pages = {Table 4.2 (page 150), 8.1 (page 300)}, ' ...
'howpublished = {\url{http://www.bio.vu.nl/thb/research/bib/Kooy2010.html}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'PappBrou2011'; type = 'article'; bib = [ ...
'author = {M. L. Pappas and G. D. Broufas and N. Koufali and P. Pieri and D. S. Koveos}, ' ... 
'title = {Effect of heat stress on survival and reproduction of the olive fruit fly \emph{Bactrocera ({D}acus) oleae}}, ' ... 
'journal = {Journal of Applied Entomology}, ' ... 
'year = {2011}, ' ... 
'volume = {135}, ' ... 
'pages = {359-366}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'HaniNati2008'; type = 'article'; bib = [ ...
'author = {Hanife Gen\c{c} and James L. Nation}, ' ... 
'title = {Survival and development of \emph{Bactrocera oleae} {G}melin ({D}iptera: {T}ephritidae) immature stages at four temperatures in the laboratory}, ' ... 
'journal = {African Journal of Biotechnology}, ' ... 
'year = {2008}, ' ... 
'volume = {7}, ' ... 
'pages = {2495-2500}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'HaniNati2008a'; type = 'article'; bib = [ ...
'author = {Hanife Gen\c{c} and James L. Nation}, ' ... 
'title = {Maintaining \emph{Bactrocera oleae} ({G}melin.) ({D}iptera: {T}ephritidae) colony on its natural host in the laboratory}, ' ... 
'journal = {J. Pest Sci.}, ' ... 
'year = {2008}, ' ... 
'volume = {81}, ' ... 
'pages = {167-174}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'Shar1980'; type = 'Article'; bib = [ ...
'author = {N.S. Sharaf}, ' ...
'year = {1980}, ' ...
'title = {Life history of the olive fruit fly, \emph{Dacus oleae} {G}mel. ({D}iptera: {T}ephritidae), and its  damage to olive fruits in {T}ripolitania}, ' ...
'journal = {Z. ang. Ent.}, ' ...
'volume = {89}, ' ...
'pages = {390-400}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'SancFern2012'; type = 'Article'; bib = [ ...
'author = {Ismael Sanchez-Ramos and Cristina E. Ferńandez and Manuel Gonz\''{a}lez-Nunez and Susana Pascual}, ' ...
'year = {2012}, ' ...
'title = {Laboratory tests of insect growth regulatorsas bait sprays for the control of the olive fruitfly, \emph{Bactrocera oleae} ({D}iptera: {T}ephritidae)}, ' ...
'journal = {Pest Manag. Sc.}, ' ...
'volume = {69}, ' ...
'pages = {520-526}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'Yoko2012'; type = 'Article'; bib = [ ...
'author = {Victoriay Yokoyama}, ' ...
'year = {2012}, ' ...
'title = {Olive Fruit Fly ({D}iptera: {T}ephritidae) in {C}alifornia: Longevity, Oviposition,and Development in Canning Olives in the Laboratory and Greenhouse}, ' ...
'journal = {J.Econ.Entomol}, ' ...
'volume = {105}, ' ...
'pages = {186-195}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'Mano1980'; type = 'Article'; bib = [ ...
'author = {Manoukas, A.G.}, ' ...
'year = {1980}, ' ...
'title = {Growth and survival of \emph{Dacus oleae} ({G}mel.) larvae underdifferent population densities}, ' ...
'journal = {Z. ang. Ent.}, ' ...
'volume = {89}, ' ...
'pages = {259-263}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
