function [data, auxData, metaData, txtData, weights] = mydata_Drosophila_melanogaster
% file generated by prt_mydata

%% set metaData
metaData.phylum     = 'Arthropoda';
metaData.class      = 'Insecta';
metaData.order      = 'Diptera';
metaData.family     = 'Drosophilidae';
metaData.species    = 'Drosophila_melanogaster';
metaData.species_en = 'fruit fly';

metaData.ecoCode.climate = {'A','B','C'};      % tropical–subtropical–temperate; cosmopolitan distribution
metaData.ecoCode.ecozone = {'TH','TN','TPa'};  % tropical humid, temperate nemoral, anthropogenic/peri-urban
metaData.ecoCode.habitat = {'0eTer','eiTi'};   % terrestrial; human-associated terrestrial habitats
metaData.ecoCode.embryo  = {'Th'};             % terrestrial, lecithotrophic eggs
metaData.ecoCode.migrate = {};                 % no migratory behaviour
metaData.ecoCode.food    = {'bjD','0iHs'};     % detritus/yeast substrates; human-associated food sources
metaData.ecoCode.gender  = {'D'};              % dioecious
metaData.ecoCode.reprod  = {'O'};              % oviparous

metaData.T_typical  = C2K(25); % K, body temp

metaData.data_0     = {'E0','ab','t1','t2','tj','Lb','L1','L2','Lj','ae','Wd_e','R','am'};
metaData.data_1     = {'tWw','tWd_f','tWd_m','tWd','tS','tSC','tL','tS_f','tR_f'};

metaData.COMPLETE   = 1; % using criteria of LikaKear2011

metaData.author     = {'Panagiotis Sakagiannis'};
metaData.date_subm  = [2026 1 1];
metaData.email      = {'p.sakagiannis@uni-koeln.de'};
metaData.address    = {'University Cologne'};

metaData.curator    = {'Dina Lika'};
metaData.email_cur  = {'lika@uoc.gr'};
metaData.date_acc   = [0 0 29];

%% zero-variate

%  -------------------- Embryo energy -------------------- 
data.E0 = 1.0e-2;           units.E0 = {'J'};   label.E0 = {'initial reserve','E_0 at fertilization'};      bibkey.E0 = {'Song2019'};       temp.E0 = C2K(25);      units.temp.E0 = 'K';    label.temp.E0 = 'temperature';

%  -------------------- Timing -------------------- 
data.ab = 0.7;              units.ab = 'd';     label.ab = 'age at birth';                                  bibkey.ab = {'Schu2020'};       temp.ab = C2K(25);      units.temp.ab = 'K';    label.temp.ab = 'temperature';
data.t1 = 1.9;              units.t1 = 'd';     label.t1 = 'duration of instar 1';                          bibkey.t1 = {'Schu2020'};       temp.t1 = C2K(25);      units.temp.t1 = 'K';    label.temp.t1 = 'temperature';
data.t2 = 1.6;              units.t2 = 'd';     label.t2 = 'duration of instar 2';                          bibkey.t2 = {'Schu2020'};       temp.t2 = C2K(25);      units.temp.t2 = 'K';    label.temp.t2 = 'temperature';
data.tj = 7.8;              units.tj = 'd';     label.tj = 'time since birth at pupation';                  bibkey.tj = {'Schu2020'};       temp.tj = C2K(25);      units.temp.tj = 'K';    label.temp.tj = 'temperature';

data.tj_F424  = 11.5;   units.tj_F424 = {'d'}; label.tj_F424 = {'time to 50% pupation','F424'};         bibkey.tj_F424 = {'Orme2017'};  temp.tj_F424 = C2K(21); units.temp.tj_F424 = 'K'; label.temp.tj_F424 = 'temperature';
data.tj_JAZZ  = 9.9125;   units.tj_JAZZ = {'d'}; label.tj_JAZZ = {'time to 50% pupation','JAZZ'};         bibkey.tj_JAZZ = {'Orme2017'};  temp.tj_JAZZ = C2K(21); units.temp.tj_JAZZ = 'K'; label.temp.tj_JAZZ = 'temperature';

data.ae_f = 9.6667;         units.ae_f={'d'};   label.ae_f={'egg to eclosion development time','female'};   bibkey.ae_f={'Bha2004'};        temp.ae_f=C2K(25);      units.temp.ae_f='K';    label.temp.ae_f='temperature';
data.am_BD_LD = 57.94;      units.am_BD_LD={'d'}; label.am_BD_LD={'mean adult lifespan','BD (LD)'};         bibkey.am_BD_LD={'YaSh2014'};   temp.am_BD_LD=C2K(25);  units.temp.am_BD_LD='K'; label.temp.am_BD_LD='temperature';

%  -------------------- Lengths -------------------- 
data.Lb = 0.06;             units.Lb = 'cm';    label.Lb = 'physical length of young instar 1';             bibkey.Lb = {'Schu2020'};
data.L1 = 0.13;             units.L1 = 'cm';    label.L1 = 'physical length at end of instar 1';            bibkey.L1 = {'Schu2020'};
data.L2 = 0.25;             units.L2 = 'cm';    label.L2 = 'physical length at end of instar 2';            bibkey.L2 = {'Schu2020'};
data.Lj = 0.38;             units.Lj = 'cm';    label.Lj = 'physical length of pupa';                       bibkey.Lj = {'Schu2020'};

data.Lw_e_f_F424 = 0.188;    units.Lw_e_f_F424={'cm'}; label.Lw_e_f_F424={'adult wing length','female, F424'};  bibkey.Lw_e_f_F424={'Orme2017'}; temp.Lw_e_f_F424=C2K(21); units.temp.Lw_e_f_F424='K'; label.temp.Lw_e_f_F424='temperature';
data.Lw_e_f_JAZZ = 0.216;    units.Lw_e_f_JAZZ={'cm'}; label.Lw_e_f_JAZZ={'adult wing length','female, JAZZ'};   bibkey.Lw_e_f_JAZZ={'Orme2017'}; temp.Lw_e_f_JAZZ=C2K(21); units.temp.Lw_e_f_JAZZ='K'; label.temp.Lw_e_f_JAZZ='temperature';

%  -------------------- Weights -------------------- 
data.Wd_e_f = 0.35e-3;      units.Wd_e_f={'g'}; label.Wd_e_f={'dry weight at eclosion','female'};           bibkey.Wd_e_f={'Bha2004'}; temp.Wd_e_f=C2K(25); units.temp.Wd_e_f='K'; label.temp.Wd_e_f='temperature';

data.Ww_e_F424 = 7.75;      units.Ww_e_F424 = {'mg'}; label.Ww_e_F424 = {'adult wet mass','female, F424'};  bibkey.Ww_e_F424 = {'Orme2017'}; temp.Ww_e_F424 = C2K(21); units.temp.Ww_e_F424 = 'K'; label.temp.Ww_e_F424 = 'temperature';
data.Ww_e_JAZZ = 9.30;      units.Ww_e_JAZZ={'mg'}; label.Ww_e_JAZZ={'adult wet mass','female, JAZZ'}; bibkey.Ww_e_JAZZ={'Orme2017'}; temp.Ww_e_JAZZ=C2K(21); units.temp.Ww_e_JAZZ='K'; label.temp.Ww_e_JAZZ='temperature';

%  -------------------- Fecundity -------------------- 
data.R = 11.2;              units.R={'#/d'};    label.R={'mean daily fecundity (first 10 d)','eggs per female per day'}; bibkey.R={'Bha2004'}; temp.R=C2K(25); units.temp.R='K'; label.temp.R='temperature';

%% uni-variate

data.tWw_f = [1 0.05; 1.5 0.20; 2 0.60; 2.5 1.40; 3 1.90; 3.5 1.70; 4 1.55; 5 1.30; 6 1.28; 7 1.27; 8 1.25; 9 1.05]; units.tWw_f = {'d','mg'}; label.tWw_f = {'age since egg laying','body mass (female)'}; bibkey.tWw_f = {'Testa2013'}; temp.tWw_f = C2K(25); units.temp.tWw_f='K'; label.temp.tWw_f='temperature';

% -------------------- survivorship curves (% vs age, d) --------------------
data.tS_BD_LD=[0 100;20 95;35 80;50 55;60 35;70 15;80 2]; units.tS_BD_LD={'d','%'}; label.tS_BD_LD={'age','adult survivorship (BD; LD)'}; bibkey.tS_BD_LD={'YaSh2014'}; temp.tS_BD_LD=C2K(25); units.temp.tS_BD_LD='K'; label.temp.tS_BD_LD='temperature';
data.tS_BD_LD_f_starved = [0 100; 0.42 99; 0.83 95; 1.25 85; 1.67 60; 2.08 35; 2.29 25; 2.50 15; 2.71 8; 2.92 2]; units.tS_BD_LD_f_starved={'d','%'}; label.tS_BD_LD_f_starved={'starvation duration','survivorship (BD f, LD)'}; bibkey.tS_BD_LD_f_starved={'YaSh2014'}; temp.tS_BD_LD_f_starved=C2K(25); units.temp.tS_BD_LD_f_starved='K'; label.temp.tS_BD_LD_f_starved='temperature';

data.tS_C  = [0 100.0;5 96.5;10 95.5;15 95.5;20 94.7;25 93.3;30 91.8;35 89.4;40 86.7;45 83.5;50 76.3;55 64.8;60 51.2;65 39.6;70 24.8;75 13.0;80 6.1;85 4.6;90 4.2;95 4.2;100 4.2]; units.tS_C={'d','%'};  label.tS_C={'age','survivorship (C)'};   bibkey.tS_C={'Ngo2019'};  temp.tS_C=C2K(23);  units.temp.tS_C='K';  label.temp.tS_C='temperature';
data.tS_DR = [0 95.2;5 95.2;10 95.2;15 95.2;20 95.2;25 94.2;30 93.6;35 92.5;40 90.9;45 88.7;50 84.5;55 77.7;60 67.8;65 55.5;70 41.6;75 26.6;80 12.6;85 6.0;90 3.7;95 3.7;100 3.7]; units.tS_DR={'d','%'}; label.tS_DR={'age','survivorship (DR)'}; bibkey.tS_DR={'Ngo2019'}; temp.tS_DR=C2K(23); units.temp.tS_DR='K'; label.temp.tS_DR='temperature';
data.tS_HS = [0 96.1;5 96.1;10 96.1;15 95.3;20 95.3;25 93.0;30 88.7;35 82.2;40 72.3;45 61.9;50 49.3;55 35.0;60 20.7;65 10.0;70 4.2;75 3.7;80 3.7;85 3.7;90 3.7;95 3.7;100 3.7]; units.tS_HS={'d','%'}; label.tS_HS={'age','survivorship (HS)'}; bibkey.tS_HS={'Ngo2019'}; temp.tS_HS=C2K(23); units.temp.tS_HS='K'; label.temp.tS_HS='temperature';

% -------------------- fecundity mean curves (eggs/female/d vs age, d) --------------------
data.tR_C  = [5 50;10 49;15 47;20 44;25 40;30 33;35 26;40 19;45 12;50 7;55 4;60 2;65 1;70 0.5;75 0.2];      units.tR_C={'d','#/d'};  label.tR_C={'age','fecundity (C)'};    bibkey.tR_C={'Ngo2019'};  temp.tR_C=C2K(23);  units.temp.tR_C='K';  label.temp.tR_C='temperature';
data.tR_DR = [5 38;10 40;15 41;20 41;25 39;30 35;35 30;40 24;45 17;50 11;55 7;60 4;65 2;70 1;75 0.3];       units.tR_DR={'d','#/d'}; label.tR_DR={'age','fecundity (DR)'};  bibkey.tR_DR={'Ngo2019'}; temp.tR_DR=C2K(23); units.temp.tR_DR='K'; label.temp.tR_DR='temperature';
data.tR_HS = [5 30;10 34;15 36;20 34;25 30;30 24;35 18;40 13;45 9;50 6;55 4;60 2.5;65 1.2;70 0.6;75 0.2];   units.tR_HS={'d','#/d'}; label.tR_HS={'age','fecundity (HS)'};  bibkey.tR_HS={'Ngo2019'}; temp.tR_HS=C2K(23); units.temp.tR_HS='K'; label.temp.tR_HS='temperature';

%% set weights for all real data
weights = setweights(data, []);
%% set pseudodata and respective weights
[data, units, label, weights] = addpseudodata(data, units, label, weights);

%% pack auxData and txtData for output
auxData.temp = temp;
txtData.units = units;
txtData.label = label;
txtData.bibkey = bibkey;
%txtData.comment = comment;

%% Links
metaData.links.id_CoL = '37S48'; % Cat of Life
metaData.links.id_EoL = '733739'; % Ency of Life
metaData.links.id_Wiki = 'Drosophila_melanogaster'; % Wikipedia
metaData.links.id_ADW = 'Drosophila_melanogaster'; % Anim Div. Web
metaData.links.id_Taxo = '29014'; % Taxonomicon
metaData.links.id_WoRMS = '';

%% References

%
bibkey = 'Schu2020'; type = 'article'; bib = [ ...
'author = {Schumann, Isabell and Triphan, Tilman}, ' ... 
'year = {2020}, ' ... 
'title = {The PEDtracker: An Automatic Staging Approach for Drosophila mel}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];

%
bibkey='Song2019'; type='article';
bib=['author={Song, Y. and Park, J.O. and Tanner, L. and Nagano, Y. and Rabinowitz, J.D. and Shvartsman, S.Y.}, ' ...
     'year={2019}, title={Energy budget of Drosophila embryogenesis}, ' ...
     'journal={Current Biology}, volume={29}, pages={R551--R567}, doi={10.1016/j.cub.2019.05.025}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];


%
bibkey = 'ChRo1966';
type   = 'article';
bib    = [ ...
  'author = {Church, Robert B. and Robertson, Forbes W.}, ' ...
  'year = {1966}, ' ...
  'title = {A Biochemical Study of the Growth of Drosophila melanogaster}, ' ...
  'journal = {Journal of Experimental Zoology}, ' ...
  'volume = {162}, ' ...
  'pages = {337--352}' ];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];

%
bibkey = 'YaSh2014';
type   = 'article';
bib    = [ ...
  'author = {Yadav, Pankaj and Sharma, Vijay Kumar}, ' ...
  'year = {2014}, ' ...
  'title = {Correlated changes in life history traits in response to selection for faster pre-adult development in Drosophila melanogaster}, ' ...
  'journal = {Journal of Experimental Biology}, ' ...
  'volume = {217}, ' ...
  'pages = {580--589}, ' ...
  'doi = {10.1242/jeb.093864}' ];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];

%
bibkey='Bha2004'; type='article'; bib=[ ...
'author = {Bharathi, N. S. and Prasad, N. G. and Shakarad, M. and Joshi, A.}, ' ...
'year = {2004}, ' ...
'title = {Correlates of sexual dimorphism for dry weight and development time in Drosophila melanogaster: a test of the differential equilibrium hypothesis}, ' ...
'journal = {Journal of Zoology}, ' ...
'volume = {264}, ' ...
'pages = {87--95}' ];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];

% --- bib entry
bibkey='Testa2013'; type='article'; bib=[ ...
'author = {Testa, Nicholas D. and Ghosh, Shampa M. and Shingleton, Alexander W.}, ' ...
'year = {2013}, ' ...
'title = {Sex-Specific Weight Loss Mediates Sexual Size Dimorphism in Drosophila melanogaster}, ' ...
'journal = {PLoS ONE}, ' ...
'volume = {8}, ' ...
'number = {3}, ' ...
'pages = {e58936}, ' ...
'doi = {10.1371/journal.pone.0058936}' ];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];

%
bibkey = 'Orme2017'; type = 'article';
bib = [ ...
 'author = {Ormerod, K.G. and LePine, O.K. and Abbineni, P.S. and Bridgeman, J.M. and Coorssen, J.R. and Mercier, A.J. and Tattersall, G.J.}, ' ...
 'year = {2017}, ' ...
 'title = {Drosophila development, physiology, behavior, and lifespan are influenced by altered dietary composition}, ' ...
 'journal = {Fly}, ' ...
 'volume = {11}, ' ...
 'number = {3}, ' ...
 'pages = {153--170}' ];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];

% 
bibkey='Ngo2019'; type='article'; bib=[ ...
'author = {Ng''oma, Wilton Fidelis and Middleton, Kevin M. and King, Elizabeth G.}, ' ...
'year = {2019}, ' ...
'title = {The evolutionary potential of diet-dependent effects on lifespan and fecundity in a multi-parental population of Drosophila melanogaster}, ' ...
'journal = {Heredity}, ' ...
'volume = {122}, ' ...
'pages = {582--594}, ' ...
'doi = {10.1038/s41437-018-0154-2}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];

%
bibkey = 'Kooy2010'; type = 'Book'; bib = [ ...  % used in setting of chemical parameters and pseudodata
'author = {Kooijman, S.A.L.M.}, ' ...
'year = {2010}, ' ...
'title  = {Dynamic Energy Budget theory for metabolic organisation}, ' ...
'publisher = {Cambridge Univ. Press, Cambridge}, ' ...
'pages = {Table 4.2 (page 150), 8.1 (page 300)}, ' ...
'howpublished = {\url{http://www.bio.vu.nl/thb/research/bib/Kooy2010.html}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];


