function [prdData, info] = predict_Drosophila_melanogaster(par, data, auxData)
% file generated by prt_predict

% unpack par, data, auxData
cPar = parscomp_st(par); vars_pull(par);
v2struct(par); v2struct(cPar); v2struct(data); v2struct(auxData);

% compute temperature correction factors
pars_T = T_A;
TC_ab = tempcorr(temp.ab, T_ref, pars_T);
TC_am = tempcorr(temp.am, T_ref, pars_T);
TC_tj = tempcorr(temp.tj, T_ref, pars_T);
TC_te = tempcorr(temp.te, T_ref, pars_T);
TC_t1 = tempcorr(temp.t1, T_ref, pars_T);
TC_t2 = tempcorr(temp.t2, T_ref, pars_T);
TC_t3 = tempcorr(temp.t3, T_ref, pars_T);
TC_Ri = tempcorr(temp.Ri, T_ref, pars_T);
TC_tWw = tempcorr(temp.tWw, T_ref, pars_T);


% life cycle
pars_tj = [g k v_Hb v_He s_j kap kap_V];
[tau_j, tau_e, tau_b, l_j, l_e, l_b, rho_j, v_Rj, u_Ee, info] = get_tj_hex(pars_tj, f);



if info == 0
  prdData = []; return;
end

% initial
pars_UE0 = [V_Hb; g; k_J; k_M; v]; % compose parameter vector
U_E0 = initial_scaled_reserve(f, pars_UE0); % d.cm^2, initial scaled reserve
E_0 = p_Am * U_E0; % J, initial reserve
Ww_0 = U_E0 * p_Am * w_E/ mu_E/ d_V; % g, initial wet weight

% birth
a_b = t_0 + tau_b/ k_M/ TC_ab;    % d, age at birth

% instars
L_b = L_m * l_b;                  % cm, structural length at birth
L_1 = L_b * s_1^0.5; % cm, structural length at 1st instar
L_2 = L_1 * s_2^0.5; % cm, structural length at 2nd instar
% L_3 = L_2 * s_3^0.5; % cm, structural length at 3rd instar
L_j = L_m * l_j; % cm, structural length at pupation
r_j = g * k_M * (f/ l_b - 1)/ (f + g); % 1/d, specific growth rate
t_1 = log(L_1/ L_b) * 3/ r_j/ TC_t1; % d, time since birth at 1st instar
t_2 = log(L_2/ L_1) * 3/ r_j/ TC_t2; % d, time since 1st instar at 2nd instar
t_3 = log(L_j/ L_2) * 3/ r_j/ TC_t3; % d, time since 2nd instar at 3rd instar
Lw_b = L_b/ del_M; % cm, physical length at birth
Lw_1 = L_1/ del_M; % cm, physical length at 1st instar
Lw_2 = L_2/ del_M; % cm, physical length at 2nd instar
Lw_3 = L_j/ del_M; % cm, physical length at 3rd instar

% pupation
L_j = L_m * l_j; % cm, structural length at pupation
t_j = (tau_j - tau_b)/ k_M/ TC_tj; % d, time since birth at pupation
Lw_j = L_j/ del_M;                % cm, physical length at pupation
%Ww_j = L_j^3 * (1 + f * w); % g, wet weight at pupation, excluding reprod buffer at pupation
E_Rj = v_Rj * (1 - kap) * g * E_m * L_j^3; % J, reproduction buffer at pupation
%Ww_j = Ww_j + E_Rj * w_E/ mu_E/ d_E; % g, wet weight including reprod buffer
u_Ej = l_j^3 * (kap * kap_V + f/ g); 
E_j = u_Ej* g * E_m * L_m^3;
Ww_j = L_j^3 * d_V + (E_Rj+E_j) * w_E/ mu_E; % g, wet weight including reprod buffer

% emergence
L_e = L_m * l_e; % cm, structural length at emergence
t_e = (tau_e - tau_j)/ k_M/ TC_te; % d, time since pupation at emergence
E_Rj = v_Rj * (1 - kap) * g * E_m * L_j^3; % J, reproduction buffer at pupation
E_e = u_Ee * g * E_m * L_m^3;  % J, reserve at emergence
%Ww_e = L_e^3 + w_E * E_e/ mu_E/ d_E; % g, wet weight at emergence
Ww_e = L_e^3 * d_E + w_E * (E_e + E_Rj)/ mu_E; % g, wet weight at emergence


% ultimate
pars_tm = [g; l_T; h_a/ k_M^2; s_G]; % compose parameter vector
tau_m = get_tm_s(pars_tm, f, l_b); % -, scaled mean life span
a_m = tau_m/ k_M/ TC_am; % d, mean life span

% reproduction
s_M = l_j/ l_b; % -, acceleration factor
R_i = kap_R * TC_Ri * (p_Am * s_M * L_e^2 - p_M * L_e^3 - k_J * E_He)/ E_0; % #/d, ultimate reproduction rate

% pack to output
prdData.ab = a_b;
prdData.am = a_m;
prdData.tj = t_j;
prdData.t1 = t_1;
prdData.t2 = t_2;
prdData.t3 = t_3;
prdData.te = t_e;

prdData.Lb = Lw_b;
prdData.L1 = Lw_1;
prdData.L2 = Lw_2;
% prdData.L3 = Lw_3;
prdData.Lj = Lw_j;
prdData.Ww0 = Ww_0;
prdData.Wwj = Ww_j;
prdData.Wwe = Ww_e;
prdData.Ri = R_i;
prdData.E0 = E_0;

% time - wet weight
L_b = L_m * get_lb([g; k; v_Hb], f_tWw); L_i = f_tWw * L_m; % cm, structural lengths
r_B = TC_tWw * k_M/ 3/ (1 + f_tWw/ g); % 1/d, von Bertalanffy growth rate
L = L_i - (L_i - L_b) * exp( - r_B * tWw(:,1)); % cm, structural length
tWw = L.^3 * (1 + f_tWw * ome); % g, wet weight

% pack to output
prdData.tWw = tWw;

%disp([tau_j, tau_e, tau_b, l_j, l_e, l_b])
%disp([a_b,t_j])

