function [data, auxData, metaData, txtData, weights] = mydata_Drosophila_melanogaster
% file generated by prt_mydata

%% set metaData
metaData.phylum     = 'Arthropoda';
metaData.class      = 'Insecta';
metaData.order      = 'Diptera';
metaData.family     = 'Drosophilidae';
metaData.species    = 'Drosophila_melanogaster';
metaData.species_en = 'fruit fly';

metaData.ecoCode.climate = {'A','B','C'};      % tropical–subtropical–temperate; cosmopolitan distribution
metaData.ecoCode.ecozone = {'TH','TN','TPa'};  % tropical humid, temperate nemoral, anthropogenic/peri-urban
metaData.ecoCode.habitat = {'0eTer','eiTi'};   % terrestrial; human-associated terrestrial habitats
metaData.ecoCode.embryo  = {'Th'};             % terrestrial, lecithotrophic eggs
metaData.ecoCode.migrate = {};                 % no migratory behaviour
metaData.ecoCode.food    = {'bjD','0iHs'};     % detritus/yeast substrates; human-associated food sources
metaData.ecoCode.gender  = {'D'};              % dioecious
metaData.ecoCode.reprod  = {'O'};              % oviparous

metaData.T_typical  = C2K(25); % K, body temp

metaData.data_0     = {'E0','ab','t1','t2','tj','Lb','L1','L2','Lj','ae','Wd_e','R','am'};
metaData.data_1     = {'tWw','tWd_f','tWd_m','tWd','tS','tSC','tL','tS_f','tR_f'};

metaData.COMPLETE   = 1; % using criteria of LikaKear2011

metaData.author     = {'Panagiotis Sakagiannis'};
metaData.date_subm  = [2026 1 1];
metaData.email      = {'p.sakagiannis@uni-koeln.de'};
metaData.address    = {'University Cologne'};

metaData.curator    = {'Dina Lika'};
metaData.email_cur  = {'lika@uoc.gr'};
metaData.date_acc   = [0 0 29];

%=============================================================
% Drosophila melanogaster vs Bactrocera oleae (Comparative Summary)
%=============================================================
%
% Phylogeny:
%   - Both Diptera (Brachycera); diverged ~70 MYA.
%   - Closer to each other than either is to Aedes aegypti (~150 MYA).
%
% Ovary Maturation:
%   - Immature at eclosion in both.
%   - D. melanogaster matures in 2–3 d (yeast diet);
%     B. oleae in 6–10 d (protein diet).
%
% Diet:
%   - Both require sugars for energy and proteins for oogenesis.
%   - Drosophila uses yeast; Bactrocera uses natural protein sources.
%
% Sexual Dimorphism:
%   - In both, females are larger and have greater abdominal volume.
%   - Drosophila males show sex combs;
%
% Development & Lifespan:
%   - Drosophila: egg→adult ~10 d; lifespan 30–50 d @25°C.
%   - Bactrocera: egg→adult ~30–40 d; lifespan 1–2 mo.
%
% Summary:
%   - Evolutionarily close fruit flies with shared endocrine and
%     reproductive mechanisms; Drosophila is faster, more fecund, and
%     saprophytic, Bactrocera slower, less fecund, and host-specific.
%=============================================================
%% Conflicts :

% tWw in Church1966 and Testa2013
% 

%% SUMMARY OF DATA IN mydata_Drosophila_melanogaster
%
% -------------------------------------------------------------------------
% ZERO-VARIATE DATA (scalar traits)
% -------------------------------------------------------------------------
%
% Embryo
%  - E0                : initial reserve per embryo (J) from embryogenesis energy budget
%
% Pre-adult development (timing)
%  - ab                : age at hatching (days AEL; PEDtracker, Canton-S)
%  - t1, t2            : times of 1st and 2nd larval molt after hatching
%  - tj / tp           : time since birth at pupation
%  - tD_m, tD_f        : sex-specific egg-to-adult development time (h)
%  - tD                : sex-mean egg-to-adult development time
%
% Pre-adult survivorship
%  - S_larva_*         : mean survivorship to larval stage (diet/strain specific)
%  - S_pupa_*          : mean survivorship to pupal stage
%  - S_adult_*         : mean survivorship to adult eclosion
%
% Adult lifespan (scalar summaries)
%  - am_f_*, am_m_* : time to 50% adult mortality, sex-specific
%  - am_*              : time to 50% adult mortality, sex-mean
%  - am_BD_DD, am_FD_DD   : mean adult lifespan (BD/FD; DD)
%  - am_BD_LD, am_FD_LD   : mean adult lifespan (BD/FD; LD)
%  - am_BD, am_FD         : photoperiod-merged mean lifespan per stock
%  - am_DD, am_LD         : stock-merged mean lifespan per photoperiod
%
% Morphology
%  - Larvae (diet/strain-specific):
%      Ww_larva_*, Dw_larva_* : wet and dry mass
%      L_larva_*,  W_larva_*  : body length and width
%  - Adults:
%      Lw_e_m_*, Lw_e_f_*   : wing length, sex-specific
%      Lw_e_*               : wing length, sex-mean
%      Ww_e_*            : adult wet mass (females)
%
% Reproduction
%  - Ri / R              : mean daily fecundity (eggs female^-1 day^-1)
%
% -------------------------------------------------------------------------
% UNI-VARIATE DATA (curves)
% -------------------------------------------------------------------------
%
% Growth
%  - tWw_f, tWw_m        : wet weight vs age, females and males
%  - tWw                : sex-merged wet weight vs age
%  - tWd_f, tWd_m        : dry weight vs age, females and males (Pacific strain)
%  - tWd                : sex-merged dry weight vs age
%
% Stress resistance (Yadav & Sharma 2014)
%  - Starvation survivorship (% vs h):
%      tS_FD_DD_m/f, tS_BD_DD_m/f : sex-specific, DD
%      tS_FD_LD_m/f, tS_BD_LD_m/f : sex-specific, LD
%      tS_FD_DD, tS_BD_DD         : sex-merged, DD
%      tS_FD_LD, tS_BD_LD         : sex-merged, LD
%      tS_FD, tS_BD               : photoperiod-merged
%      tS                         : stock-merged (BD+FD)
%
%  - Starvation + desiccation survivorship (% vs h):
%      analogous hierarchy of datasets:
%      sex-specific → sex-merged → photoperiod-merged → stock-merged
%      final merged dataset: tSC
%
% Adult survivorship curves
%  - tL_FD_DD, tL_BD_DD  : FD/BD, DD
%  - tL_FD_LD, tL_BD_LD  : FD/BD, LD
%  - tL_FD, tL_BD        : photoperiod-merged
%  - tL                  : stock-merged adult survivorship curve
%
% Diet-dependent adult performance (Ng'oma et al.)
%  - Adult survivorship vs age:
%      tS_C, tS_DR, tS_HS : control, dietary restriction, high sugar
%      tS_diets           : diet-mean survivorship
%  - Fecundity vs age:
%      tR_C, tR_DR, tR_HS : diet-specific fecundity curves
%      tR_diets           : diet-mean fecundity curve
%
% -------------------------------------------------------------------------
% Notes
%  - Raw condition-specific datasets are preserved alongside explicitly
%    merged datasets (sex-, photoperiod-, diet-, or stock-mean).
%  - Temperature is specified per dataset when differing from the default
%    metaData.T_typical = 25 °C.
%  - Data span the full life cycle (embryo → larva → pupa → adult) and
%    support integrated DEB parameter estimation.



%% Song et al. (2019) Curr Biol 29:R551–R567: D. melanogaster embryogenesis energy budget;
%  non-feeding embryo ⇒ initial reserve equals total mobilized energy; calorimetry/respirometry/biochemistry; total heat dissipated fertilization→hatching ≈ 10 mJ per embryo.

data.E0 = 1.0e-2; units.E0 = {'J'}; label.E0 = {'initial reserve','E_0 at fertilization'}; bibkey.E0 = {'Song2019'}; temp.E0 = C2K(25); units.temp.E0 = 'K'; label.temp.E0 = 'temperature';

%% Schumann I & Triphan T (2020) The PEDtracker: An automatic staging approach for Drosophila melanogaster larvae.
% Wild-type D. melanogaster (Canton-S). Husbandry: 25 °C, ~65% humidity, 14:10 h light:dark cycle. Tracking in climate chamber: 23–25 °C, 60–65% humidity, constant light during recording.

% Timing: hatch 0.7 d AEL; 1st molt 1.9 d AH; 2nd molt 3.5 d AH; pupation 7.8 d AH (Table 3)
data.ab = 0.7;      units.ab = 'd';     label.ab = 'age at birth';                          bibkey.ab = {'Schu2020'};   temp.ab = C2K(25);  units.temp.ab = 'K';    label.temp.ab = 'temperature';
data.t1 = 1.9;      units.t1 = 'd';     label.t1 = 'duration of instar 1';                  bibkey.t1 = {'Schu2020'};  temp.t1 = C2K(25);  units.temp.t1 = 'K';    label.temp.t1 = 'temperature';
data.t2 = 1.6;      units.t2 = 'd';     label.t2 = 'duration of instar 2';                  bibkey.t2 = {'Schu2020'};  temp.t2 = C2K(25);  units.temp.t2 = 'K';    label.temp.t2 = 'temperature';
data.tj = 7.8;      units.tj = 'd';     label.tj = 'time since birth at pupation';          bibkey.tj = {'Schu2020'};   temp.tj = C2K(25);  units.temp.tj = 'K';    label.temp.tj = 'temperature';

% Lengths: young L1 0.6 mm; late L1 1.3 mm; late L2 2.5 mm; late L3 3.8 mm (Table 4)
data.Lb = 0.06;     units.Lb = 'cm';    label.Lb = 'physical length of young instar 1';     bibkey.Lb = {'Schu2020'};
data.L1 = 0.13;     units.L1 = 'cm';    label.L1 = 'physical length at end of instar 1';    bibkey.L1 = {'Schu2020'};
data.L2 = 0.25;     units.L2 = 'cm';    label.L2 = 'physical length at end of instar 2';    bibkey.L2 = {'Schu2020'};
data.Lj = 0.38;     units.Lj = 'cm';    label.Lj = 'physical length of pupa';               bibkey.Lj = {'Schu2020'};

%% Bharathi et al. (2004) J Zool 264:87–95: D. melanogaster (JB-1 lab pop, >700 gens); 25°C, constant light, ~90% RH; banana–jaggery food; metrics digitized for D. melanogaster from Figs 1 (egg→eclosion dev time, h; m/f), 4 (larval & pupal survivorship; pre-adult=larval×pupal), 5 (dry wt at eclosion, g; m/f; axis 10^-3 g/fly), 6 (mean daily fecundity, eggs/d over first 10 d).

% data.ae_m = 234/24; 
data.ae_f = 232/24; 
% data.ae = 0.5*(data.ae_m + data.ae_f);

% data.Sl   = 0.82; data.Sp = 0.95; data.S = data.Sl*data.Sp;

% data.Wd_e_m = 0.27e-3; 
data.Wd_e_f = 0.35e-3; 
% data.Wd_e = 0.5*(data.Wd_e_m + data.Wd_e_f);

data.R    = 11.2;

% units.ae_m={'d'}; label.ae_m={'egg to eclosion development time','male'};   bibkey.ae_m={'Bha2004'}; temp.ae_m=C2K(25); units.temp.ae_m='K'; label.temp.ae_m='temperature';
units.ae_f={'d'}; label.ae_f={'egg to eclosion development time','female'}; bibkey.ae_f={'Bha2004'}; temp.ae_f=C2K(25); units.temp.ae_f='K'; label.temp.ae_f='temperature';
% units.ae  ={'d'}; label.ae  ={'egg to eclosion development time','sex-mean'}; bibkey.ae={'Bha2004'}; temp.ae=C2K(25); units.temp.ae='K'; label.temp.ae='temperature';

% units.Sl={'1'}; label.Sl={'mean survivorship','larval'};   bibkey.Sl={'Bha2004'}; temp.Sl=C2K(25); units.temp.Sl='K'; label.temp.Sl='temperature';
% units.Sp={'1'}; label.Sp={'mean survivorship','pupal'};    bibkey.Sp={'Bha2004'}; temp.Sp=C2K(25); units.temp.Sp='K'; label.temp.Sp='temperature';
% units.S ={'1'}; label.S ={'mean survivorship','pre-adult (larval×pupal)'}; bibkey.S={'Bha2004'}; temp.S=C2K(25); units.temp.S='K'; label.temp.S='temperature';

% units.Wd_e_m={'g'}; label.Wd_e_m={'dry weight at eclosion','male'};   bibkey.Wd_e_m={'Bha2004'}; temp.Wd_e_m=C2K(25); units.temp.Wd_e_m='K'; label.temp.Wd_e_m='temperature';
units.Wd_e_f={'g'}; label.Wd_e_f={'dry weight at eclosion','female'}; bibkey.Wd_e_f={'Bha2004'}; temp.Wd_e_f=C2K(25); units.temp.Wd_e_f='K'; label.temp.Wd_e_f='temperature';
% units.Wd_e  ={'g'}; label.Wd_e  ={'dry weight at eclosion','sex-mean'}; bibkey.Wd_e={'Bha2004'}; temp.Wd_e=C2K(25); units.temp.Wd_e='K'; label.temp.Wd_e='temperature';

units.R={'#/d'}; label.R={'mean daily fecundity (first 10 d)','eggs per female per day'}; bibkey.R={'Bha2004'}; temp.R=C2K(25); units.temp.R='K'; label.temp.R='temperature';

%% Church & Robertson (1966) J Exp Zool 162:337–352 — biochemical growth; Pacific strain (wild, unselected)
% Sex: wet weight measured in females; dry weight in females + males (males ~0.75 of female mass).
% Conditions: axenic culture on optimal defined medium (Sang 1956, medium C); growth comparable to live-yeast medium after burrowing;
% Temperature: ~25 °C (pupation timing discussed at 25 °C). Time axis: time since hatching (AH); pupation ~104 h AH; no pupal weight loss reported.
% Data digitized from Fig. 1 (wet weight) and Fig. 2 (dry weight), points marked "o".

% Commented out because of duplicate variable name
% data.tWw_f   = [12 0.10;24 0.35;36 0.85;48 1.45;60 1.95;72 2.16;84 2.05;96 1.90;104 1.85]; data.tWw_f(:,1)=data.tWw_f(:,1)/24;
% units.tWw_f  = {'d','mg'}; label.tWw_f  = {'time since hatching','wet weight (female)'};  bibkey.tWw_f  = {'ChRo1966'}; temp.tWw_f  = C2K(25); units.temp.tWw_f  = 'K'; label.temp.tWw_f  = 'temperature';

% data.tWd_f = [12 0.03;24 0.10;36 0.22;48 0.33;60 0.42;72 0.47;84 0.49;96 0.44;104 0.40]; data.tWd_f(:,1)=data.tWd_f(:,1)/24;
% units.tWd_f= {'d','mg'}; label.tWd_f= {'time since hatching','dry weight (female)'};  bibkey.tWd_f= {'ChRo1966'}; temp.tWd_f= C2K(25); units.temp.tWd_f= 'K'; label.temp.tWd_f= 'temperature';
% 
% data.tWd_m = [12 0.02;24 0.07;36 0.17;48 0.25;60 0.31;72 0.36;84 0.37;96 0.33;104 0.30]; data.tWd_m(:,1)=data.tWd_m(:,1)/24;
% units.tWd_m= {'d','mg'}; label.tWd_m= {'time since hatching','dry weight (male)'};    bibkey.tWd_m= {'ChRo1966'}; temp.tWd_m= C2K(25); units.temp.tWd_m= 'K'; label.temp.tWd_m= 'temperature';
% 
% % Sex-merged dry weight (equal-weight mean after interpolation on union time grid)
% t = unique([data.tWd_f(:,1); data.tWd_m(:,1)]);
% Wf = interp1(data.tWd_f(:,1), data.tWd_f(:,2), t, 'linear','extrap');
% Wm = interp1(data.tWd_m(:,1), data.tWd_m(:,2), t, 'linear','extrap');
% data.tWd = [t, 0.5*(Wf + Wm)];
% units.tWd = {'d','mg'}; label.tWd = {'time since hatching','dry weight (sex-mean)'}; bibkey.tWd = {'ChRo1966'}; temp.tWd = C2K(25); units.temp.tWd = 'K'; label.temp.tWd = 'temperature';

%% Testa et al. (2013) PLoS ONE 8:e58936 – Sex-specific growth & SSD in D. melanogaster;
%  Strain: isogenic Samarkand (SAM); Conditions: 25°C, 24h light, standard cornmeal-molasses food;
%  Metric: body mass (mg) vs age (h AEL) across larval, pupal and adult stages (Fig.1D);
%  Data digitized from mean curves (points with CI); sexes separate + sex-mean.

% --- Female
data.tWw_f = [ ...
   24 0.05; 36 0.20; 48 0.60; 60 1.40; 72 1.90; 84 1.70; 96 1.55; ...
  120 1.30; 144 1.28; 168 1.27; 192 1.25; 216 1.05 ];
data.tWw_f(:,1)=data.tWw_f(:,1)/24;

% --- Male
% data.tWw_m = [ ...
%    24 0.04; 36 0.15; 48 0.50; 60 1.10; 72 1.45; 84 1.40; 96 1.35; ...
%   120 1.10; 144 1.08; 168 1.07; 192 1.06; 216 0.90 ];
% data.tWw_m(:,1)=data.tWw_m(:,1)/24;

% --- Sex-mean (pointwise mean)
% t = unique([data.tWw_f(:,1); data.tWw_m(:,1)]);
% Wf = interp1(data.tWw_f(:,1),data.tWw_f(:,2),t,'linear','extrap');
% Wm = interp1(data.tWw_m(:,1),data.tWw_m(:,2),t,'linear','extrap');
% data.tWw = [t, 0.5*(Wf + Wm)];

% --- metadata
units.tWw_f = {'d','mg'}; label.tWw_f = {'age since egg laying','body mass (female)'}; bibkey.tWw_f = {'Testa2013'}; temp.tWw_f = C2K(25); units.temp.tWw_f='K'; label.temp.tWw_f='temperature';
% units.tWw_m = {'d','mg'}; label.tWw_m = {'age since egg laying','body mass (male)'};   bibkey.tWw_m = {'Testa2013'}; temp.tWw_m = C2K(25); units.temp.tWw_m='K'; label.temp.tWw_m='temperature';
% units.tWw   = {'d','mg'}; label.tWw   = {'age since egg laying','body mass (sex-mean)'};bibkey.tWw   = {'Testa2013'}; temp.tWw   = C2K(25); units.temp.tWw  ='K'; label.temp.tWw  ='temperature';

%% Ormerod et al. (2017) Fly 11:153–170 — Diet-dependent development, morphology and lifespan in D. melanogaster
% Data extracted as zero- and univariate summaries from Fig. 1 (developmental timing, survivorship,
% adult lifespan) and Table 1 (morphology). Two larval diets compared:
% Formula 4–24 (lower protein, higher carbohydrate) vs Jazz-mix (higher protein).
% Species/strain: Drosophila melanogaster, laboratory stock (strain not further specified).
% Rearing and assays at 21 °C. Means reported; SDs omitted for DEB use.

% ------------------------
% PRE-ADULT DEVELOPMENT TIME (50% point)

% data.tDev_larva_F424 = 223.6/24;   % d, time to 50% wandering L3
% data.tDev_larva_JAZZ = 177.2/24;
data.tj_F424  = 276.1/24;   % d, time to 50% pupation
data.tj_JAZZ  = 237.9/24;

% units.tDev_larva_F424 = {'d'}; label.tDev_larva_F424 = {'time to 50% wandering L3','F424'}; bibkey.tDev_larva_F424 = {'Orme2017'}; temp.tDev_larva_F424 = C2K(21); units.temp.tDev_larva_F424 = 'K'; label.temp.tDev_larva_F424 = 'temperature';
% units.tDev_larva_JAZZ = {'d'}; label.tDev_larva_JAZZ = {'time to 50% wandering L3','JAZZ'}; bibkey.tDev_larva_JAZZ = {'Orme2017'}; temp.tDev_larva_JAZZ = C2K(21); units.temp.tDev_larva_JAZZ = 'K'; label.temp.tDev_larva_JAZZ = 'temperature';

units.tj_F424 = {'d'}; label.tj_F424 = {'time to 50% pupation','F424'}; bibkey.tj_F424 = {'Orme2017'}; temp.tj_F424 = C2K(21); units.temp.tj_F424 = 'K'; label.temp.tj_F424 = 'temperature';
units.tj_JAZZ = {'d'}; label.tj_JAZZ = {'time to 50% pupation','JAZZ'}; bibkey.tj_JAZZ = {'Orme2017'}; temp.tj_JAZZ = C2K(21); units.temp.tj_JAZZ = 'K'; label.temp.tj_JAZZ = 'temperature';

% ------------------------
% MEAN SURVIVORSHIP TO STAGE

% data.S_larva_F424 = 94.8;   % %
% data.S_larva_JAZZ = 91.6;
% data.S_pupa_F424  = 90.8;
% data.S_pupa_JAZZ  = 89.2;
% data.S_adult_F424 = 88.4;
% data.S_adult_JAZZ = 87.2;
% 
% units.S_larva_F424 = {'%'}; label.S_larva_F424 = {'mean survivorship to larva','F424'}; bibkey.S_larva_F424 = {'Orme2017'}; temp.S_larva_F424 = C2K(21); units.temp.S_larva_F424 = 'K'; label.temp.S_larva_F424 = 'temperature';
% units.S_pupa_F424 = {'%'}; label.S_pupa_F424 = {'mean survivorship to pupa','F424'}; bibkey.S_pupa_F424 = {'Orme2017'}; temp.S_pupa_F424 = C2K(21); units.temp.S_pupa_F424 = 'K'; label.temp.S_pupa_F424 = 'temperature';
% units.S_adult_F424 = {'%'}; label.S_adult_F424 = {'mean survivorship to adult','F424'}; bibkey.S_adult_F424 = {'Orme2017'}; temp.S_adult_F424 = C2K(21); units.temp.S_adult_F424 = 'K'; label.temp.S_adult_F424 = 'temperature';
% units.S_larva_JAZZ = {'%'}; label.S_larva_JAZZ = {'mean survivorship to larva','JAZZ'}; bibkey.S_larva_JAZZ = {'Orme2017'}; temp.S_larva_JAZZ = C2K(21); units.temp.S_larva_JAZZ = 'K'; label.temp.S_larva_JAZZ = 'temperature';
% units.S_pupa_JAZZ  = {'%'}; label.S_pupa_JAZZ  = {'mean survivorship to pupa','JAZZ'};  bibkey.S_pupa_JAZZ  = {'Orme2017'}; temp.S_pupa_JAZZ  = C2K(21); units.temp.S_pupa_JAZZ  = 'K'; label.temp.S_pupa_JAZZ  = 'temperature';
% units.S_adult_JAZZ = {'%'}; label.S_adult_JAZZ = {'mean survivorship to adult','JAZZ'}; bibkey.S_adult_JAZZ = {'Orme2017'}; temp.S_adult_JAZZ = C2K(21); units.temp.S_adult_JAZZ = 'K'; label.temp.S_adult_JAZZ = 'temperature';

% ------------------------
% ADULT LIFESPAN (50% mortality)

% data.am_f_F424 = 47.1;   % d
% data.am_f_JAZZ = 63.6;
% data.am_m_F424 = 29.1;
% data.am_m_JAZZ = 49.7;
% data.am_F424   = mean([data.am_f_F424, data.am_m_F424]);
% data.am_JAZZ   = mean([data.am_f_JAZZ, data.am_m_JAZZ]);

% units.am_f_F424={'d'}; label.am_f_F424={'time to 50% adult mortality','female, F424'}; bibkey.am_f_F424={'Orme2017'}; temp.am_f_F424=C2K(21); units.temp.am_f_F424='K'; label.temp.am_f_F424='temperature';
% units.am_f_JAZZ={'d'}; label.am_f_JAZZ={'time to 50% adult mortality','female, JAZZ'};  bibkey.am_f_JAZZ={'Orme2017'}; temp.am_f_JAZZ=C2K(21); units.temp.am_f_JAZZ='K'; label.temp.am_f_JAZZ='temperature';
% units.am_m_F424={'d'}; label.am_m_F424={'time to 50% adult mortality','male, F424'};    bibkey.am_m_F424={'Orme2017'}; temp.am_m_F424=C2K(21); units.temp.am_m_F424='K'; label.temp.am_m_F424='temperature';
% units.am_m_JAZZ={'d'}; label.am_m_JAZZ={'time to 50% adult mortality','male, JAZZ'};     bibkey.am_m_JAZZ={'Orme2017'}; temp.am_m_JAZZ=C2K(21); units.temp.am_m_JAZZ='K'; label.temp.am_m_JAZZ='temperature';
% units.am_F424={'d'}; label.am_F424={'time to 50% adult mortality','sex-mean, F424'}; bibkey.am_F424={'Orme2017'}; temp.am_F424=C2K(21); units.temp.am_F424='K'; label.temp.am_F424='temperature';
% units.am_JAZZ={'d'}; label.am_JAZZ={'time to 50% adult mortality','sex-mean, JAZZ'}; bibkey.am_JAZZ={'Orme2017'}; temp.am_JAZZ=C2K(21); units.temp.am_JAZZ='K'; label.temp.am_JAZZ='temperature';

% ------------------------
% MORPHOLOGY — LARVAE (measured at the wandering state)

% data.Ww_larva_F424 = 11.17;  % mg
% data.Ww_larva_JAZZ = 19.42;
% data.Dw_larva_F424 = 2.60;   % mg
% data.Dw_larva_JAZZ = 5.51;
% data.L_larva_F424  = 3.69;   % mm
% data.L_larva_JAZZ  = 3.89;
% data.W_larva_F424  = 0.66;   % mm
% data.W_larva_JAZZ  = 1.00;
% 
% units.Ww_larva_F424 = {'mg'}; label.Ww_larva_F424 = {'larval wet mass','F424'}; bibkey.Ww_larva_F424 = {'Orme2017'}; temp.Ww_larva_F424 = C2K(21); units.temp.Ww_larva_F424 = 'K'; label.temp.Ww_larva_F424 = 'temperature';
% units.Dw_larva_F424 = {'mg'}; label.Dw_larva_F424 = {'larval dry mass','F424'}; bibkey.Dw_larva_F424 = {'Orme2017'}; temp.Dw_larva_F424 = C2K(21); units.temp.Dw_larva_F424 = 'K'; label.temp.Dw_larva_F424 = 'temperature';
% units.Ww_larva_JAZZ={'mg'}; label.Ww_larva_JAZZ={'larval wet mass','JAZZ'}; bibkey.Ww_larva_JAZZ={'Orme2017'}; temp.Ww_larva_JAZZ=C2K(21); units.temp.Ww_larva_JAZZ='K'; label.temp.Ww_larva_JAZZ='temperature';
% units.Dw_larva_JAZZ={'mg'}; label.Dw_larva_JAZZ={'larval dry mass','JAZZ'}; bibkey.Dw_larva_JAZZ={'Orme2017'}; temp.Dw_larva_JAZZ=C2K(21); units.temp.Dw_larva_JAZZ='K'; label.temp.Dw_larva_JAZZ='temperature';
% units.L_larva_F424={'mm'}; label.L_larva_F424={'larval length','F424'};     bibkey.L_larva_F424={'Orme2017'}; temp.L_larva_F424=C2K(21); units.temp.L_larva_F424='K'; label.temp.L_larva_F424='temperature';
% units.L_larva_JAZZ={'mm'}; label.L_larva_JAZZ={'larval length','JAZZ'};      bibkey.L_larva_JAZZ={'Orme2017'}; temp.L_larva_JAZZ=C2K(21); units.temp.L_larva_JAZZ='K'; label.temp.L_larva_JAZZ='temperature';
% units.W_larva_F424={'mm'}; label.W_larva_F424={'larval width','F424'};       bibkey.W_larva_F424={'Orme2017'}; temp.W_larva_F424=C2K(21); units.temp.W_larva_F424='K'; label.temp.W_larva_F424='temperature';
% units.W_larva_JAZZ={'mm'}; label.W_larva_JAZZ={'larval width','JAZZ'};        bibkey.W_larva_JAZZ={'Orme2017'}; temp.W_larva_JAZZ=C2K(21); units.temp.W_larva_JAZZ='K'; label.temp.W_larva_JAZZ='temperature';

% ------------------------
% MORPHOLOGY — ADULTS

% data.Lw_e_m_F424 = 1.77;  % mm
% data.Lw_e_m_JAZZ = 1.90;
data.Lw_e_f_F424 = 1.88;
data.Lw_e_f_JAZZ = 2.16;
% data.Lw_e_F424   = mean([data.Lw_e_m_F424, data.Lw_e_f_F424]);
% data.Lw_e_JAZZ   = mean([data.Lw_e_m_JAZZ, data.Lw_e_f_JAZZ]);

data.Ww_e_F424 = 7.75;  % mg (females)
data.Ww_e_JAZZ = 9.30;



% units.Lw_e_m_F424={'mm'}; label.Lw_e_m_F424={'adult wing length','male, F424'};   bibkey.Lw_e_m_F424={'Orme2017'}; temp.Lw_e_m_F424=C2K(21); units.temp.Lw_e_m_F424='K'; label.temp.Lw_e_m_F424='temperature';
% units.Lw_e_m_JAZZ={'mm'}; label.Lw_e_m_JAZZ={'adult wing length','male, JAZZ'};    bibkey.Lw_e_m_JAZZ={'Orme2017'}; temp.Lw_e_m_JAZZ=C2K(21); units.temp.Lw_e_m_JAZZ='K'; label.temp.Lw_e_m_JAZZ='temperature';
units.Lw_e_f_F424={'mm'}; label.Lw_e_f_F424={'adult wing length','female, F424'};  bibkey.Lw_e_f_F424={'Orme2017'}; temp.Lw_e_f_F424=C2K(21); units.temp.Lw_e_f_F424='K'; label.temp.Lw_e_f_F424='temperature';
units.Lw_e_f_JAZZ={'mm'}; label.Lw_e_f_JAZZ={'adult wing length','female, JAZZ'};   bibkey.Lw_e_f_JAZZ={'Orme2017'}; temp.Lw_e_f_JAZZ=C2K(21); units.temp.Lw_e_f_JAZZ='K'; label.temp.Lw_e_f_JAZZ='temperature';

% units.Lw_e_JAZZ={'mm'}; label.Lw_e_JAZZ={'adult wing length','sex-mean, JAZZ'}; bibkey.Lw_e_JAZZ={'Orme2017'}; temp.Lw_e_JAZZ=C2K(21); units.temp.Lw_e_JAZZ='K'; label.temp.Lw_e_JAZZ='temperature';
% units.Lw_e_F424 = {'mm'}; label.Lw_e_F424 = {'adult wing length','sex-mean, F424'}; bibkey.Lw_e_F424 = {'Orme2017'}; temp.Lw_e_F424 = C2K(21); units.temp.Lw_e_F424 = 'K'; label.temp.Lw_e_F424 = 'temperature';
units.Ww_e_F424 = {'mg'}; label.Ww_e_F424 = {'adult wet mass','female, F424'}; bibkey.Ww_e_F424 = {'Orme2017'}; temp.Ww_e_F424 = C2K(21); units.temp.Ww_e_F424 = 'K'; label.temp.Ww_e_F424 = 'temperature';
units.Ww_e_JAZZ={'mg'}; label.Ww_e_JAZZ={'adult wet mass','female, JAZZ'}; bibkey.Ww_e_JAZZ={'Orme2017'}; temp.Ww_e_JAZZ=C2K(21); units.temp.Ww_e_JAZZ='K'; label.temp.Ww_e_JAZZ='temperature';

%% Yadav & Sharma (2014) JEB 217:580–589 (doi:10.1242/jeb.093864): D. melanogaster outbred BD vs FD;
%  FD = ~12% (~29 h) shorter pre-adult development after ~50–60 generations; assays at 25±0.5°C, 75±5% RH,
%  under DD or 12:12 LD; digitized (open circles) survivorship curves (%) for starvation (Fig2), starvation+desiccation (Fig3),
%  and adult lifespan (Fig4, gen50).

% -------------------- raw digitized curves --------------------
% data.tS_FD_DD_m=[0 100;10 96;20 85;30 60;40 30;50 10;60 2];
% data.tS_BD_DD_m=[0 100;10 98;20 92;30 80;40 55;50 30;60 10;70 2];
% data.tS_FD_DD_f=[0 100;10 98;20 90;30 70;40 40;50 15;60 5];
% data.tS_BD_DD_f=[0 100;10 99;20 95;30 85;40 65;50 40;60 20;70 5];

% data.tS_FD_LD_m=[0 100;10 95;20 75;25 55;30 35;35 20;40 10;45 5];
% data.tS_BD_LD_m=[0 100;10 98;20 90;30 65;40 35;50 15;55 8;60 2];
% data.tS_FD_LD_f=[0 100;10 98;20 88;30 60;40 30;45 20;50 12;55 6];
% data.tS_BD_LD_f=[0 100;10 99;20 95;30 85;40 60;50 35;55 25;60 15;65 8;70 2];
data.tS_BD_LD_f_starved=[0 100;10 99;20 95;30 85;40 60;50 35;55 25;60 15;65 8;70 2];

% data.tSD_FD_DD_m = [0 100; 6 78; 10 55; 14 30; 18 15; 22 5; 24 2];
% data.tSD_BD_DD_m = [0 100; 6 88; 10 70; 14 45; 18 25; 22 12; 24 5; 26 2];
% data.tSD_FD_DD_f=[0 100;8 92;16 70;24 30;32 10;40 2];
% data.tSD_BD_DD_f=[0 100;8 96;16 85;24 55;32 25;40 5];
% data.tSD_FD_LD_m=[0 100;6 75;9 45;12 25;15 12;18 5];
% data.tSD_BD_LD_m=[0 100;6 85;9 60;12 35;15 18;18 10;21 5;24 2];
% data.tSD_FD_LD_f=[0 100;10 92;16 70;22 45;26 30;30 18;34 8;36 2];
% data.tSD_BD_LD_f=[0 100;10 96;16 85;22 65;26 50;30 35;34 22;36 15;38 10;40 5;42 2];

% data.tL_FD_DD=[0 100;20 92;40 70;60 30;75 10;85 2];
% data.tL_BD_DD=[0 100;20 96;40 85;60 55;75 30;90 10;100 2];
% data.tL_FD_LD=[0 100;20 90;35 65;50 30;60 12;70 2];
% data.tL_BD_LD=[0 100;20 95;35 80;50 55;60 35;70 15;80 2];
data.tS_BD_LD=[0 100;20 95;35 80;50 55;60 35;70 15;80 2];


% -------------------- compact merges (sex, photoperiod, stock) --------------------
% helper inline: merge2(A,B) via union-x + interp + mean (repeated explicitly to avoid functions)

% Starvation: sex-merge within DD/LD, then photoperiod-merge, then BD+FD merge
% t=unique([data.tS_FD_DD_m(:,1);data.tS_FD_DD_f(:,1)]); data.tS_FD_DD=[t,0.5*(interp1(data.tS_FD_DD_m(:,1),data.tS_FD_DD_m(:,2),t,'linear','extrap')+interp1(data.tS_FD_DD_f(:,1),data.tS_FD_DD_f(:,2),t,'linear','extrap'))];
% t=unique([data.tS_BD_DD_m(:,1);data.tS_BD_DD_f(:,1)]); data.tS_BD_DD=[t,0.5*(interp1(data.tS_BD_DD_m(:,1),data.tS_BD_DD_m(:,2),t,'linear','extrap')+interp1(data.tS_BD_DD_f(:,1),data.tS_BD_DD_f(:,2),t,'linear','extrap'))];
% t=unique([data.tS_FD_LD_m(:,1);data.tS_FD_LD_f(:,1)]); data.tS_FD_LD=[t,0.5*(interp1(data.tS_FD_LD_m(:,1),data.tS_FD_LD_m(:,2),t,'linear','extrap')+interp1(data.tS_FD_LD_f(:,1),data.tS_FD_LD_f(:,2),t,'linear','extrap'))];
% t=unique([data.tS_BD_LD_m(:,1);data.tS_BD_LD_f(:,1)]); data.tS_BD_LD=[t,0.5*(interp1(data.tS_BD_LD_m(:,1),data.tS_BD_LD_m(:,2),t,'linear','extrap')+interp1(data.tS_BD_LD_f(:,1),data.tS_BD_LD_f(:,2),t,'linear','extrap'))];

% t=unique([data.tS_FD_DD(:,1);data.tS_FD_LD(:,1)]); data.tS_FD=[t,0.5*(interp1(data.tS_FD_DD(:,1),data.tS_FD_DD(:,2),t,'linear','extrap')+interp1(data.tS_FD_LD(:,1),data.tS_FD_LD(:,2),t,'linear','extrap'))];
% t=unique([data.tS_BD_DD(:,1);data.tS_BD_LD(:,1)]); data.tS_BD=[t,0.5*(interp1(data.tS_BD_DD(:,1),data.tS_BD_DD(:,2),t,'linear','extrap')+interp1(data.tS_BD_LD(:,1),data.tS_BD_LD(:,2),t,'linear','extrap'))];

% t=unique([data.tS_BD(:,1);data.tS_FD(:,1)]); data.tS=[t,0.5*(interp1(data.tS_BD(:,1),data.tS_BD(:,2),t,'linear','extrap')+interp1(data.tS_FD(:,1),data.tS_FD(:,2),t,'linear','extrap'))];


% Starvation+desiccation: sex-merge within DD/LD, then photoperiod-merge, then BD+FD merge
% t=unique([data.tSD_FD_DD_m(:,1);data.tSD_FD_DD_f(:,1)]); data.tSD_FD_DD=[t,0.5*(interp1(data.tSD_FD_DD_m(:,1),data.tSD_FD_DD_m(:,2),t,'linear','extrap')+interp1(data.tSD_FD_DD_f(:,1),data.tSD_FD_DD_f(:,2),t,'linear','extrap'))];
% t=unique([data.tSD_BD_DD_m(:,1);data.tSD_BD_DD_f(:,1)]); data.tSD_BD_DD=[t,0.5*(interp1(data.tSD_BD_DD_m(:,1),data.tSD_BD_DD_m(:,2),t,'linear','extrap')+interp1(data.tSD_BD_DD_f(:,1),data.tSD_BD_DD_f(:,2),t,'linear','extrap'))];
% 
% t=unique([data.tSD_FD_LD_m(:,1);data.tSD_FD_LD_f(:,1)]); data.tSD_FD_LD=[t,0.5*(interp1(data.tSD_FD_LD_m(:,1),data.tSD_FD_LD_m(:,2),t,'linear','extrap')+interp1(data.tSD_FD_LD_f(:,1),data.tSD_FD_LD_f(:,2),t,'linear','extrap'))];
% t=unique([data.tSD_BD_LD_m(:,1);data.tSD_BD_LD_f(:,1)]); data.tSD_BD_LD=[t,0.5*(interp1(data.tSD_BD_LD_m(:,1),data.tSD_BD_LD_m(:,2),t,'linear','extrap')+interp1(data.tSD_BD_LD_f(:,1),data.tSD_BD_LD_f(:,2),t,'linear','extrap'))];
% 
% t=unique([data.tSD_FD_DD(:,1);data.tSD_FD_LD(:,1)]); data.tSD_FD=[t,0.5*(interp1(data.tSD_FD_DD(:,1),data.tSD_FD_DD(:,2),t,'linear','extrap')+interp1(data.tSD_FD_LD(:,1),data.tSD_FD_LD(:,2),t,'linear','extrap'))];
% t=unique([data.tSD_BD_DD(:,1);data.tSD_BD_LD(:,1)]); data.tSD_BD=[t,0.5*(interp1(data.tSD_BD_DD(:,1),data.tSD_BD_DD(:,2),t,'linear','extrap')+interp1(data.tSD_BD_LD(:,1),data.tSD_BD_LD(:,2),t,'linear','extrap'))];
% 
% t=unique([data.tSD_BD(:,1);data.tSD_FD(:,1)]); data.tSC=[t,0.5*(interp1(data.tSD_BD(:,1),data.tSD_BD(:,2),t,'linear','extrap')+interp1(data.tSD_FD(:,1),data.tSD_FD(:,2),t,'linear','extrap'))];


% Adult lifespan: DD+LD merge within stock, then BD+FD merge
% t=unique([data.tL_FD_DD(:,1);data.tL_FD_LD(:,1)]); data.tL_FD=[t,0.5*(interp1(data.tL_FD_DD(:,1),data.tL_FD_DD(:,2),t,'linear','extrap')+interp1(data.tL_FD_LD(:,1),data.tL_FD_LD(:,2),t,'linear','extrap'))];
% t=unique([data.tL_BD_DD(:,1);data.tL_BD_LD(:,1)]); data.tL_BD=[t,0.5*(interp1(data.tL_BD_DD(:,1),data.tL_BD_DD(:,2),t,'linear','extrap')+interp1(data.tL_BD_LD(:,1),data.tL_BD_LD(:,2),t,'linear','extrap'))];
% t=unique([data.tL_BD(:,1);data.tL_FD(:,1)]); data.tL=[t,0.5*(interp1(data.tL_BD(:,1),data.tL_BD(:,2),t,'linear','extrap')+interp1(data.tL_FD(:,1),data.tL_FD(:,2),t,'linear','extrap'))];


% -------------------- compact metadata helpers --------------------
T25 = C2K(25);

% units.tS_FD_DD_m={'h','%'}; label.tS_FD_DD_m={'starvation duration','survivorship (FD m, DD)'}; bibkey.tS_FD_DD_m={'YaSh2014'}; temp.tS_FD_DD_m=T25; units.temp.tS_FD_DD_m='K'; label.temp.tS_FD_DD_m='temperature';
% units.tS_BD_DD_m={'h','%'}; label.tS_BD_DD_m={'starvation duration','survivorship (BD m, DD)'}; bibkey.tS_BD_DD_m={'YaSh2014'}; temp.tS_BD_DD_m=T25; units.temp.tS_BD_DD_m='K'; label.temp.tS_BD_DD_m='temperature';
% units.tS_FD_DD_f={'h','%'}; label.tS_FD_DD_f={'starvation duration','survivorship (FD f, DD)'}; bibkey.tS_FD_DD_f={'YaSh2014'}; temp.tS_FD_DD_f=T25; units.temp.tS_FD_DD_f='K'; label.temp.tS_FD_DD_f='temperature';
% units.tS_BD_DD_f={'h','%'}; label.tS_BD_DD_f={'starvation duration','survivorship (BD f, DD)'}; bibkey.tS_BD_DD_f={'YaSh2014'}; temp.tS_BD_DD_f=T25; units.temp.tS_BD_DD_f='K'; label.temp.tS_BD_DD_f='temperature';

% units.tS_FD_LD_m={'h','%'}; label.tS_FD_LD_m={'starvation duration','survivorship (FD m, LD)'}; bibkey.tS_FD_LD_m={'YaSh2014'}; temp.tS_FD_LD_m=T25; units.temp.tS_FD_LD_m='K'; label.temp.tS_FD_LD_m='temperature';
% units.tS_BD_LD_m={'h','%'}; label.tS_BD_LD_m={'starvation duration','survivorship (BD m, LD)'}; bibkey.tS_BD_LD_m={'YaSh2014'}; temp.tS_BD_LD_m=T25; units.temp.tS_BD_LD_m='K'; label.temp.tS_BD_LD_m='temperature';
% units.tS_FD_LD_f={'h','%'}; label.tS_FD_LD_f={'starvation duration','survivorship (FD f, LD)'}; bibkey.tS_FD_LD_f={'YaSh2014'}; temp.tS_FD_LD_f=T25; units.temp.tS_FD_LD_f='K'; label.temp.tS_FD_LD_f='temperature';
%units.tS_BD_LD_f={'h','%'}; label.tS_BD_LD_f={'starvation duration','survivorship (BD f, LD)'}; bibkey.tS_BD_LD_f={'YaSh2014'}; temp.tS_BD_LD_f=T25; units.temp.tS_BD_LD_f='K'; label.temp.tS_BD_LD_f='temperature';
units.tS_BD_LD_f_starved={'h','%'}; label.tS_BD_LD_f_starved={'starvation duration','survivorship (BD f, LD)'}; bibkey.tS_BD_LD_f_starved={'YaSh2014'}; temp.tS_BD_LD_f_starved=T25; units.temp.tS_BD_LD_f_starved='K'; label.temp.tS_BD_LD_f_starved='temperature';

% units.tS_FD_DD={'h','%'}; label.tS_FD_DD={'starvation duration','survivorship (FD; DD; sexes merged)'}; bibkey.tS_FD_DD={'YaSh2014'}; temp.tS_FD_DD=T25; units.temp.tS_FD_DD='K'; label.temp.tS_FD_DD='temperature';
% units.tS_BD_DD={'h','%'}; label.tS_BD_DD={'starvation duration','survivorship (BD; DD; sexes merged)'}; bibkey.tS_BD_DD={'YaSh2014'}; temp.tS_BD_DD=T25; units.temp.tS_BD_DD='K'; label.temp.tS_BD_DD='temperature';
% units.tS_FD_LD={'h','%'}; label.tS_FD_LD={'starvation duration','survivorship (FD; LD; sexes merged)'}; bibkey.tS_FD_LD={'YaSh2014'}; temp.tS_FD_LD=T25; units.temp.tS_FD_LD='K'; label.temp.tS_FD_LD='temperature';
% units.tS_BD_LD={'h','%'}; label.tS_BD_LD={'starvation duration','survivorship (BD; LD; sexes merged)'}; bibkey.tS_BD_LD={'YaSh2014'}; temp.tS_BD_LD=T25; units.temp.tS_BD_LD='K'; label.temp.tS_BD_LD='temperature';
% units.tS_FD={'h','%'}; label.tS_FD={'starvation duration','survivorship (FD; DD+LD; sexes merged)'}; bibkey.tS_FD={'YaSh2014'}; temp.tS_FD=T25; units.temp.tS_FD='K'; label.temp.tS_FD='temperature';
% units.tS_BD={'h','%'}; label.tS_BD={'starvation duration','survivorship (BD; DD+LD; sexes merged)'}; bibkey.tS_BD={'YaSh2014'}; temp.tS_BD=T25; units.temp.tS_BD='K'; label.temp.tS_BD='temperature';
% units.tS={'h','%'}; label.tS={'starvation duration','survivorship (BD+FD; DD+LD; sexes merged)'}; bibkey.tS={'YaSh2014'}; temp.tS=T25; units.temp.tS='K'; label.temp.tS='temperature';


% units.tSD_FD_DD_m={'h','%'}; label.tSD_FD_DD_m={'starvation+desiccation duration','survivorship (FD m, DD)'}; bibkey.tSD_FD_DD_m={'YaSh2014'}; temp.tSD_FD_DD_m = C2K(25); units.temp.tSD_FD_DD_m = 'K'; label.temp.tSD_FD_DD_m = 'temperature';
% units.tSD_BD_DD_m={'h','%'}; label.tSD_BD_DD_m={'starvation+desiccation duration','survivorship (BD m, DD)'}; bibkey.tSD_BD_DD_m={'YaSh2014'}; temp.tSD_BD_DD_m = C2K(25); units.temp.tSD_BD_DD_m = 'K'; label.temp.tSD_BD_DD_m = 'temperature';
% units.tSD_FD_DD_f={'h','%'}; label.tSD_FD_DD_f={'starvation+desiccation duration','survivorship (FD f, DD)'}; bibkey.tSD_FD_DD_f={'YaSh2014'}; temp.tSD_FD_DD_f=T25; units.temp.tSD_FD_DD_f='K'; label.temp.tSD_FD_DD_f='temperature';
% units.tSD_BD_DD_f={'h','%'}; label.tSD_BD_DD_f={'starvation+desiccation duration','survivorship (BD f, DD)'}; bibkey.tSD_BD_DD_f={'YaSh2014'}; temp.tSD_BD_DD_f=T25; units.temp.tSD_BD_DD_f='K'; label.temp.tSD_BD_DD_f='temperature';
% units.tSD_FD_LD_m={'h','%'}; label.tSD_FD_LD_m={'starvation+desiccation duration','survivorship (FD m, LD)'}; bibkey.tSD_FD_LD_m={'YaSh2014'}; temp.tSD_FD_LD_m=T25; units.temp.tSD_FD_LD_m='K'; label.temp.tSD_FD_LD_m='temperature';
% units.tSD_BD_LD_m={'h','%'}; label.tSD_BD_LD_m={'starvation+desiccation duration','survivorship (BD m, LD)'}; bibkey.tSD_BD_LD_m={'YaSh2014'}; temp.tSD_BD_LD_m=T25; units.temp.tSD_BD_LD_m='K'; label.temp.tSD_BD_LD_m='temperature';
% units.tSD_FD_LD_f={'h','%'}; label.tSD_FD_LD_f={'starvation+desiccation duration','survivorship (FD f, LD)'}; bibkey.tSD_FD_LD_f={'YaSh2014'}; temp.tSD_FD_LD_f=T25; units.temp.tSD_FD_LD_f='K'; label.temp.tSD_FD_LD_f='temperature';
% units.tSD_BD_LD_f={'h','%'}; label.tSD_BD_LD_f={'starvation+desiccation duration','survivorship (BD f, LD)'}; bibkey.tSD_BD_LD_f={'YaSh2014'}; temp.tSD_BD_LD_f=T25; units.temp.tSD_BD_LD_f='K'; label.temp.tSD_BD_LD_f='temperature';
% 
% units.tSD_FD_DD={'h','%'}; label.tSD_FD_DD={'starvation+desiccation duration','survivorship (FD; DD; sexes merged)'}; bibkey.tSD_FD_DD={'YaSh2014'}; temp.tSD_FD_DD=T25; units.temp.tSD_FD_DD='K'; label.temp.tSD_FD_DD='temperature';
% units.tSD_BD_DD={'h','%'}; label.tSD_BD_DD={'starvation+desiccation duration','survivorship (BD; DD; sexes merged)'}; bibkey.tSD_BD_DD={'YaSh2014'}; temp.tSD_BD_DD=T25; units.temp.tSD_BD_DD='K'; label.temp.tSD_BD_DD='temperature';
% units.tSD_FD_LD={'h','%'}; label.tSD_FD_LD={'starvation+desiccation duration','survivorship (FD; LD; sexes merged)'}; bibkey.tSD_FD_LD={'YaSh2014'}; temp.tSD_FD_LD=T25; units.temp.tSD_FD_LD='K'; label.temp.tSD_FD_LD='temperature';
% units.tSD_BD_LD={'h','%'}; label.tSD_BD_LD={'starvation+desiccation duration','survivorship (BD; LD; sexes merged)'}; bibkey.tSD_BD_LD={'YaSh2014'}; temp.tSD_BD_LD=T25; units.temp.tSD_BD_LD='K'; label.temp.tSD_BD_LD='temperature';
% units.tSD_FD={'h','%'}; label.tSD_FD={'starvation+desiccation duration','survivorship (FD; DD+LD; sexes merged)'}; bibkey.tSD_FD={'YaSh2014'}; temp.tSD_FD=T25; units.temp.tSD_FD='K'; label.temp.tSD_FD='temperature';
% units.tSD_BD={'h','%'}; label.tSD_BD={'starvation+desiccation duration','survivorship (BD; DD+LD; sexes merged)'}; bibkey.tSD_BD={'YaSh2014'}; temp.tSD_BD=T25; units.temp.tSD_BD='K'; label.temp.tSD_BD='temperature';
% units.tSC={'h','%'}; label.tSC={'starvation+desiccation duration','survivorship (BD+FD; DD+LD; sexes merged)'}; bibkey.tSC={'YaSh2014'}; temp.tSC=T25; units.temp.tSC='K'; label.temp.tSC='temperature';

% units.tL_FD_DD={'d','%'}; label.tL_FD_DD={'age','adult survivorship (FD; DD)'}; bibkey.tL_FD_DD={'YaSh2014'}; temp.tL_FD_DD=T25; units.temp.tL_FD_DD='K'; label.temp.tL_FD_DD='temperature';
% units.tL_BD_DD={'d','%'}; label.tL_BD_DD={'age','adult survivorship (BD; DD)'}; bibkey.tL_BD_DD={'YaSh2014'}; temp.tL_BD_DD=T25; units.temp.tL_BD_DD='K'; label.temp.tL_BD_DD='temperature';
% units.tL_FD_LD={'d','%'}; label.tL_FD_LD={'age','adult survivorship (FD; LD)'}; bibkey.tL_FD_LD={'YaSh2014'}; temp.tL_FD_LD=T25; units.temp.tL_FD_LD='K'; label.temp.tL_FD_LD='temperature';
% units.tL_BD_LD={'d','%'}; label.tL_BD_LD={'age','adult survivorship (BD; LD)'}; bibkey.tL_BD_LD={'YaSh2014'}; temp.tL_BD_LD=T25; units.temp.tL_BD_LD='K'; label.temp.tL_BD_LD='temperature';
units.tS_BD_LD={'d','%'}; label.tS_BD_LD={'age','adult survivorship (BD; LD)'}; bibkey.tS_BD_LD={'YaSh2014'}; temp.tS_BD_LD=T25; units.temp.tS_BD_LD='K'; label.temp.tS_BD_LD='temperature';

% units.tL_FD={'d','%'}; label.tL_FD={'age','adult survivorship (FD; DD+LD merged)'}; bibkey.tL_FD={'YaSh2014'}; temp.tL_FD=T25; units.temp.tL_FD='K'; label.temp.tL_FD='temperature';
% units.tL_BD={'d','%'}; label.tL_BD={'age','adult survivorship (BD; DD+LD merged)'}; bibkey.tL_BD={'YaSh2014'}; temp.tL_BD=T25; units.temp.tL_BD='K'; label.temp.tL_BD='temperature';
% units.tL={'d','%'}; label.tL={'age','adult survivorship (BD+FD; DD+LD merged)'}; bibkey.tL={'YaSh2014'}; temp.tL=T25; units.temp.tL='K'; label.temp.tL='temperature';

% Fig.4C (Gen50) – mean adult lifespan bars (d): digitized BD/FD under DD/LD; then DD+LD mean; then BD+FD mean
% data.am_BD_DD = 65.57; 
% data.am_FD_DD = 52.85; 
data.am_BD_LD = 57.94; 
% data.am_FD_LD = 46.55;   % days
% data.am_BD = 0.5*(data.am_BD_DD + data.am_BD_LD);  data.am_FD = 0.5*(data.am_FD_DD + data.am_FD_LD);
% data.am = 0.5*(data.am_BD + data.am_FD);

% units.am_BD_DD={'d'}; label.am_BD_DD={'mean adult lifespan','BD (DD)'}; bibkey.am_BD_DD={'YaSh2014'}; temp.am_BD_DD=C2K(25); units.temp.am_BD_DD='K'; label.temp.am_BD_DD='temperature';
% units.am_FD_DD={'d'}; label.am_FD_DD={'mean adult lifespan','FD (DD)'}; bibkey.am_FD_DD={'YaSh2014'}; temp.am_FD_DD=C2K(25); units.temp.am_FD_DD='K'; label.temp.am_FD_DD='temperature';
units.am_BD_LD={'d'}; label.am_BD_LD={'mean adult lifespan','BD (LD)'}; bibkey.am_BD_LD={'YaSh2014'}; temp.am_BD_LD=C2K(25); units.temp.am_BD_LD='K'; label.temp.am_BD_LD='temperature';
% units.am_FD_LD={'d'}; label.am_FD_LD={'mean adult lifespan','FD (LD)'}; bibkey.am_FD_LD={'YaSh2014'}; temp.am_FD_LD=C2K(25); units.temp.am_FD_LD='K'; label.temp.am_FD_LD='temperature';

% units.am_BD={'d'}; label.am_BD={'mean adult lifespan','BD (DD+LD mean)'}; bibkey.am_BD={'YaSh2014'}; temp.am_BD=C2K(25); units.temp.am_BD='K'; label.temp.am_BD='temperature';
% units.am_FD={'d'}; label.am_FD={'mean adult lifespan','FD (DD+LD mean)'}; bibkey.am_FD={'YaSh2014'}; temp.am_FD=C2K(25); units.temp.am_FD='K'; label.temp.am_FD='temperature';
% units.am={'d'};    label.am={'mean adult lifespan','BD+FD mean (DD+LD mean)'}; bibkey.am={'YaSh2014'}; temp.am=C2K(25); units.temp.am='K'; label.temp.am='temperature';




%% Ng'oma, Middleton & King (2019) Heredity 122:582–594 (doi:10.1038/s41437-018-0154-2) — Diet-dependent lifespan & fecundity in D. melanogaster (DSPR multi-parental pop)
% Diets: C (control), DR (dietary restriction; reduced yeast/protein vs C), HS (high sugar vs C); conditions: 23°C (see Methods for full husbandry).
% Univariate data digitized from Fig. survival panel (b): survivorship (%) vs age (d), and Fig. fecundity panel (a): eggs per female vs age (d) (black mean curve).
% Also computes mean curves across diets for survivorship and fecundity (equal-weight across C/DR/HS via interpolation on union age grid).

% -------------------- survivorship curves (% vs age, d) --------------------
data.tS_C  = [0 100.0;5 96.5;10 95.5;15 95.5;20 94.7;25 93.3;30 91.8;35 89.4;40 86.7;45 83.5;50 76.3;55 64.8;60 51.2;65 39.6;70 24.8;75 13.0;80 6.1;85 4.6;90 4.2;95 4.2;100 4.2];
data.tS_DR = [0 95.2;5 95.2;10 95.2;15 95.2;20 95.2;25 94.2;30 93.6;35 92.5;40 90.9;45 88.7;50 84.5;55 77.7;60 67.8;65 55.5;70 41.6;75 26.6;80 12.6;85 6.0;90 3.7;95 3.7;100 3.7];
data.tS_HS = [0 96.1;5 96.1;10 96.1;15 95.3;20 95.3;25 93.0;30 88.7;35 82.2;40 72.3;45 61.9;50 49.3;55 35.0;60 20.7;65 10.0;70 4.2;75 3.7;80 3.7;85 3.7;90 3.7;95 3.7;100 3.7];

% -------------------- fecundity mean curves (eggs/female/d vs age, d) --------------------
data.tR_C  = [5 50;10 49;15 47;20 44;25 40;30 33;35 26;40 19;45 12;50 7;55 4;60 2;65 1;70 0.5;75 0.2];
data.tR_DR = [5 38;10 40;15 41;20 41;25 39;30 35;35 30;40 24;45 17;50 11;55 7;60 4;65 2;70 1;75 0.3];
data.tR_HS = [5 30;10 34;15 36;20 34;25 30;30 24;35 18;40 13;45 9;50 6;55 4;60 2.5;65 1.2;70 0.6;75 0.2];

% -------------------- mean curves across diets (equal weight; union age grid) --------------------
% t = unique([data.tS_C(:,1); data.tS_DR(:,1); data.tS_HS(:,1)]);
% SC  = interp1(data.tS_C(:,1),  data.tS_C(:,2),  t,'linear','extrap');
% SDR = interp1(data.tS_DR(:,1), data.tS_DR(:,2), t,'linear','extrap');
% SHS = interp1(data.tS_HS(:,1), data.tS_HS(:,2), t,'linear','extrap');
% data.tS_diets = [t, (SC+SDR+SHS)/3];
% 
% t = unique([data.tR_C(:,1); data.tR_DR(:,1); data.tR_HS(:,1)]);
% RC  = interp1(data.tR_C(:,1),  data.tR_C(:,2),  t,'linear','extrap');
% RDR = interp1(data.tR_DR(:,1), data.tR_DR(:,2), t,'linear','extrap');
% RHS = interp1(data.tR_HS(:,1), data.tR_HS(:,2), t,'linear','extrap');
% data.tR_diets = [t, (RC+RDR+RHS)/3];

% -------------------- metadata --------------------
units.tS_C={'d','%'};  label.tS_C={'age','survivorship (C)'};   bibkey.tS_C={'Ngo2019'};  temp.tS_C=C2K(23);  units.temp.tS_C='K';  label.temp.tS_C='temperature';
units.tS_DR={'d','%'}; label.tS_DR={'age','survivorship (DR)'}; bibkey.tS_DR={'Ngo2019'}; temp.tS_DR=C2K(23); units.temp.tS_DR='K'; label.temp.tS_DR='temperature';
units.tS_HS={'d','%'}; label.tS_HS={'age','survivorship (HS)'}; bibkey.tS_HS={'Ngo2019'}; temp.tS_HS=C2K(23); units.temp.tS_HS='K'; label.temp.tS_HS='temperature';
% units.tS_diets={'d','%'}; label.tS_diets={'age','survivorship (C+DR+HS mean)'}; bibkey.tS_diets={'Ngo2019'}; temp.tS_diets=C2K(23); units.temp.tS_diets='K'; label.temp.tS_diets='temperature';

units.tR_C={'d','#/d'};  label.tR_C={'age','fecundity (C)'};    bibkey.tR_C={'Ngo2019'};  temp.tR_C=C2K(23);  units.temp.tR_C='K';  label.temp.tR_C='temperature';
units.tR_DR={'d','#/d'}; label.tR_DR={'age','fecundity (DR)'};  bibkey.tR_DR={'Ngo2019'}; temp.tR_DR=C2K(23); units.temp.tR_DR='K'; label.temp.tR_DR='temperature';
units.tR_HS={'d','#/d'}; label.tR_HS={'age','fecundity (HS)'};  bibkey.tR_HS={'Ngo2019'}; temp.tR_HS=C2K(23); units.temp.tR_HS='K'; label.temp.tR_HS='temperature';
% units.tR_diets={'d','#/d'}; label.tR_diets={'age','fecundity (C+DR+HS mean)'}; bibkey.tR_diets={'Ngo2019'}; temp.tR_diets=C2K(23); units.temp.tR_diets='K'; label.temp.tR_diets='temperature';


%% set weights for all real data
weights = setweights(data, []);
%% set pseudodata and respective weights
[data, units, label, weights] = addpseudodata(data, units, label, weights);

%% pack auxData and txtData for output
auxData.temp = temp;
txtData.units = units;
txtData.label = label;
txtData.bibkey = bibkey;
%txtData.comment = comment;

%% Links
metaData.links.id_CoL = '37S48'; % Cat of Life
metaData.links.id_EoL = '733739'; % Ency of Life
metaData.links.id_Wiki = 'Drosophila_melanogaster'; % Wikipedia
metaData.links.id_ADW = 'Drosophila_melanogaster'; % Anim Div. Web
metaData.links.id_Taxo = '29014'; % Taxonomicon
metaData.links.id_WoRMS = '';

%% References

%
bibkey = 'Schu2020'; type = 'article'; bib = [ ...
'author = {Schumann, Isabell and Triphan, Tilman}, ' ... 
'year = {2020}, ' ... 
'title = {The PEDtracker: An Automatic Staging Approach for Drosophila mel}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];

%
bibkey='Song2019'; type='article';
bib=['author={Song, Y. and Park, J.O. and Tanner, L. and Nagano, Y. and Rabinowitz, J.D. and Shvartsman, S.Y.}, ' ...
     'year={2019}, title={Energy budget of Drosophila embryogenesis}, ' ...
     'journal={Current Biology}, volume={29}, pages={R551--R567}, doi={10.1016/j.cub.2019.05.025}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];


%
bibkey = 'ChRo1966';
type   = 'article';
bib    = [ ...
  'author = {Church, Robert B. and Robertson, Forbes W.}, ' ...
  'year = {1966}, ' ...
  'title = {A Biochemical Study of the Growth of Drosophila melanogaster}, ' ...
  'journal = {Journal of Experimental Zoology}, ' ...
  'volume = {162}, ' ...
  'pages = {337--352}' ];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];

%
bibkey = 'YaSh2014';
type   = 'article';
bib    = [ ...
  'author = {Yadav, Pankaj and Sharma, Vijay Kumar}, ' ...
  'year = {2014}, ' ...
  'title = {Correlated changes in life history traits in response to selection for faster pre-adult development in Drosophila melanogaster}, ' ...
  'journal = {Journal of Experimental Biology}, ' ...
  'volume = {217}, ' ...
  'pages = {580--589}, ' ...
  'doi = {10.1242/jeb.093864}' ];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];

%
bibkey='Bha2004'; type='article'; bib=[ ...
'author = {Bharathi, N. S. and Prasad, N. G. and Shakarad, M. and Joshi, A.}, ' ...
'year = {2004}, ' ...
'title = {Correlates of sexual dimorphism for dry weight and development time in Drosophila melanogaster: a test of the differential equilibrium hypothesis}, ' ...
'journal = {Journal of Zoology}, ' ...
'volume = {264}, ' ...
'pages = {87--95}' ];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];

% --- bib entry
bibkey='Testa2013'; type='article'; bib=[ ...
'author = {Testa, Nicholas D. and Ghosh, Shampa M. and Shingleton, Alexander W.}, ' ...
'year = {2013}, ' ...
'title = {Sex-Specific Weight Loss Mediates Sexual Size Dimorphism in Drosophila melanogaster}, ' ...
'journal = {PLoS ONE}, ' ...
'volume = {8}, ' ...
'number = {3}, ' ...
'pages = {e58936}, ' ...
'doi = {10.1371/journal.pone.0058936}' ];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];

%
bibkey = 'Orme2017'; type = 'article';
bib = [ ...
 'author = {Ormerod, K.G. and LePine, O.K. and Abbineni, P.S. and Bridgeman, J.M. and Coorssen, J.R. and Mercier, A.J. and Tattersall, G.J.}, ' ...
 'year = {2017}, ' ...
 'title = {Drosophila development, physiology, behavior, and lifespan are influenced by altered dietary composition}, ' ...
 'journal = {Fly}, ' ...
 'volume = {11}, ' ...
 'number = {3}, ' ...
 'pages = {153--170}' ];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];

% 
bibkey='Ngo2019'; type='article'; bib=[ ...
'author = {Ng''oma, Wilton Fidelis and Middleton, Kevin M. and King, Elizabeth G.}, ' ...
'year = {2019}, ' ...
'title = {The evolutionary potential of diet-dependent effects on lifespan and fecundity in a multi-parental population of Drosophila melanogaster}, ' ...
'journal = {Heredity}, ' ...
'volume = {122}, ' ...
'pages = {582--594}, ' ...
'doi = {10.1038/s41437-018-0154-2}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];

%
bibkey = 'Kooy2010'; type = 'Book'; bib = [ ...  % used in setting of chemical parameters and pseudodata
'author = {Kooijman, S.A.L.M.}, ' ...
'year = {2010}, ' ...
'title  = {Dynamic Energy Budget theory for metabolic organisation}, ' ...
'publisher = {Cambridge Univ. Press, Cambridge}, ' ...
'pages = {Table 4.2 (page 150), 8.1 (page 300)}, ' ...
'howpublished = {\url{http://www.bio.vu.nl/thb/research/bib/Kooy2010.html}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];


